/* ============================================================
   BASE DE DATOS DE EJERCICIOS
   ------------------------------------------------------------
   Esto es una base de EJEMPLO para que el generador funcione
   de punta a punta. La idea es que la vayas reemplazando por
   tu contenido real (o el de la instructora que lo valide).

   Cada ejercicio tiene esta forma:

   {
     id: string único
     discipline: "pilates" | "yoga"
     name: string
     position: string (texto libre, ej "Supino", "De pie")
     modality: ["mat","reformer"] o ["suave","dinamico","restaurativo"]
     level: ["inicial","intermedio","avanzado"]
     moment: 1 a 6  -> a qué bloque de la clase pertenece
     objective: ["id-de-objetivo", ...]
     avoid: ["tag-contraindicacion", ...]  (opcional)
     description: texto que ve la alumna/instructora
     howTo: cómo explicarlo (opcional)
     adaptation: adaptación por patología (opcional, texto orientativo)
     seriesDefault: número de series sugeridas
   }
   ============================================================ */

const BLOCKS = [
  { id: 1, name: "Preparación",         subtitle: "Conectar con el cuerpo y la respiración",     weight: 0.15, optional: true },
  { id: 2, name: "Activación",          subtitle: "Despertar el centro, sentar las bases",        weight: 0.17 },
  { id: 3, name: "Desarrollo Principal",subtitle: "El patrón central, ligado al objetivo elegido",weight: 0.22 },
  { id: 4, name: "Profundización",      subtitle: "Variación, carga o coordinación sobre lo aprendido", weight: 0.17 },
  { id: 5, name: "Integración",         subtitle: "Secuencia fluida que une lo trabajado",        weight: 0.14 },
  { id: 6, name: "Cierre",              subtitle: "Vuelta al eje, respiración, sensación final",  weight: 0.15 },
];

const OBJECTIVES = {
  pilates: [
    { id: "lumbopelvica", label: "Estabilidad Lumbopélvica" },
    { id: "columna", label: "Movilidad de Columna" },
    { id: "tren-superior", label: "Fuerza de Tren Superior" },
    { id: "centro", label: "Conexión con el Centro" },
  ],
  yoga: [
    { id: "enraizamiento", label: "Equilibrio y Enraizamiento" },
    { id: "cadera", label: "Apertura de Cadera" },
    { id: "columna-yoga", label: "Flexibilidad de Columna" },
    { id: "fuerza-yoga", label: "Fuerza y Estabilidad" },
  ],
};

const MODALITIES = {
  pilates: [
    { id: "mat", label: "Mat" },
    { id: "reformer", label: "Reformer" },
    { id: "mixta", label: "Mixta" },
  ],
  yoga: [
    { id: "suave", label: "Suave" },
    { id: "dinamico", label: "Dinámico" },
    { id: "restaurativo", label: "Restaurativo" },
  ],
};

const POPULATIONS = [
  { id: "general", label: "Adultos (general)" },
  { id: "mayores", label: "Adultos mayores" },
  { id: "embarazo", label: "Embarazo / posparto" },
  { id: "principiantes", label: "Principiantes absolutas" },
];

const AVOID_TAGS = [
  "Hernia de disco lumbar",
  "Embarazo / posparto",
  "Problemas de cadera / prótesis",
  "Post-cirugía de rodilla",
  "Hipermovilidad",
  "Disfunción de suelo pélvico",
];

const EXERCISES = [
  {
    id: "pilates-021",
    discipline: "pilates",
    name: "Protracción y retracción escapular en cuadrupedia",
    position: "Cuadrupedia",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio"],
    moment: 1,
    objective: ["control-escapular"],
    description: "Apoyada en manos y rodillas, dejá que el pecho caiga levemente entre los omóplatos y luego empujá el piso alejándolo, moviendo solo la escápula sin flexionar los codos.",
    howTo: "Pedí que sientan que el espacio entre los omóplatos se ensancha al empujar el piso.",
    adaptation: "Reducir el recorrido del movimiento si aparece molestia en la muñeca de apoyo.",
    seriesDefault: 2,
  },
  {
    id: "pilates-022",
    discipline: "pilates",
    name: "Reloj escapular con brazos elevados",
    position: "Supino",
    modality: ["mat"],
    level: ["intermedio"],
    moment: 2,
    objective: ["control-escapular", "tren-superior"],
    description: "Con los brazos extendidos hacia el techo, deslizá los omóplatos hacia arriba, abajo y a los costados sin mover los brazos del punto fijo, como si dibujaran un reloj sobre la colchoneta.",
    howTo: "Pedí que localicen el movimiento solo en la espalda, no en los brazos ni el cuello.",
    seriesDefault: 2,
  },
  {
    id: "pilates-023",
    discipline: "pilates",
    name: "Arm Springs — remo con control escapular",
    position: "Sentada de espaldas al cabezal",
    modality: ["reformer", "mixta"],
    level: ["intermedio", "avanzado"],
    moment: 3,
    objective: ["control-escapular", "tren-superior"],
    description: "Sentada con carga liviana en los resortes de brazos, tirá hacia atrás organizando primero el omóplato hacia abajo y luego extendiendo el codo, sosteniendo el torso estable durante todo el recorrido.",
    howTo: "Pedí que bajen el omóplato antes de que la mano se mueva, como si lo guardaran en el bolsillo trasero.",
    seriesDefault: 3,
  },
  {
    id: "pilates-024",
    discipline: "pilates",
    name: "Deslizamiento de brazos en pared (Wall Slides)",
    position: "De pie, espalda apoyada en la pared",
    modality: ["mat"],
    level: ["inicial"],
    moment: 1,
    objective: ["control-escapular", "columna"],
    description: "De espaldas contra la pared, deslizá los brazos hacia arriba y abajo manteniendo el contacto de la zona lumbar y los omóplatos, sin que las costillas se levanten al subir los brazos.",
    howTo: "Pedí que noten si la zona lumbar se despega de la pared al subir los brazos.",
    adaptation: "Reducir la altura del recorrido de los brazos si no logran mantener el apoyo lumbar.",
    seriesDefault: 2,
  },
  {
    id: "pilates-025",
    discipline: "pilates",
    name: "Plancha alta con foco en omóplatos",
    position: "Prono, apoyo en manos y pies",
    modality: ["mat", "reformer", "mixta"],
    level: ["avanzado"],
    moment: 4,
    objective: ["control-escapular", "centro"],
    avoid: ["Embarazo / posparto"],
    description: "En posición de plancha alta, dejá que el pecho caiga apenas entre los omóplatos y luego empujá el piso para separarlos, sosteniendo la línea del cuerpo firme durante el movimiento.",
    howTo: "Pedí que el movimiento sea chico: solo la caja torácica sube y baja entre los brazos.",
    adaptation: "Realizar el movimiento con las rodillas apoyadas en el piso en lugar de en plancha completa.",
    seriesDefault: 2,
  },
  {
    id: "pilates-026",
    discipline: "pilates",
    name: "Roll Up con brazos alternados",
    position: "Supino",
    modality: ["mat"],
    level: ["intermedio"],
    moment: 3,
    objective: ["coordinacion-fluidez", "columna"],
    description: "Enrollá la columna hacia arriba llevando un brazo al frente y el otro hacia atrás, alternando el lado en cada repetición mientras el torso sube y baja con control.",
    howTo: "Pedí que decidan qué brazo va adelante antes de empezar a subir, para no perder el ritmo.",
    adaptation: "Flexionar las rodillas y usar el impulso de los brazos si la zona lumbar tensa al subir.",
    seriesDefault: 2,
  },
  {
    id: "pilates-027",
    discipline: "pilates",
    name: "Footwork con cambio de ritmo en Reformer",
    position: "Supino en el carro",
    modality: ["reformer", "mixta"],
    level: ["intermedio"],
    moment: 2,
    objective: ["coordinacion-fluidez", "lumbopelvica"],
    description: "Con los pies en la barra y carga media, alterná dos empujes rápidos y uno lento en cada serie, sosteniendo la pelvis neutra mientras cambia el ritmo del movimiento.",
    howTo: "Pedí que cuenten en voz alta el patrón rápido-rápido-lento antes de empezar a moverse.",
    seriesDefault: 3,
  },
  {
    id: "pilates-028",
    discipline: "pilates",
    name: "Criss Cross alternado",
    position: "Supino",
    modality: ["mat"],
    level: ["intermedio", "avanzado"],
    moment: 4,
    objective: ["coordinacion-fluidez", "centro"],
    avoid: ["Hernia de disco lumbar"],
    description: "Con las manos detrás de la cabeza y una rodilla al pecho, rotá el torso llevando el codo contrario hacia la rodilla, alternando de lado en un ritmo continuo y controlado.",
    howTo: "Pedí que giren desde las costillas, no tironeando del cuello con las manos.",
    adaptation: "Reducir la rotación del torso y mantener la cabeza apoyada en el piso entre repeticiones.",
    seriesDefault: 2,
  },
  {
    id: "pilates-029",
    discipline: "pilates",
    name: "Brazo y pierna cruzados en Reformer",
    position: "Prono sobre el carro, manos en las correas",
    modality: ["reformer", "mixta"],
    level: ["avanzado"],
    moment: 5,
    objective: ["coordinacion-fluidez", "centro"],
    description: "Boca abajo sobre el carro, extendé un brazo hacia adelante y la pierna opuesta hacia atrás al mismo tiempo, sosteniendo el equilibrio del carro sin que se desplace de más.",
    howTo: "Pedí que el carro se mueva lo mínimo posible mientras extienden brazo y pierna.",
    adaptation: "Realizar el movimiento sin extender por completo la pierna, manteniendo apoyo parcial en la plataforma.",
    seriesDefault: 2,
  },
  {
    id: "pilates-030",
    discipline: "pilates",
    name: "Marcha lenta con cambio de apoyo",
    position: "De pie",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio"],
    moment: 2,
    objective: ["coordinacion-fluidez", "lumbopelvica"],
    description: "De pie, elevá una rodilla despacio hasta la cadera y apoyá el pie con control antes de repetir con la otra pierna, sosteniendo la pelvis estable durante todo el cambio de apoyo.",
    howTo: "Pedí que apoyen el pie sin golpear el piso, como si pisaran sobre algodón.",
    adaptation: "Apoyar una mano en una silla o pared para sostener el equilibrio.",
    seriesDefault: 2,
  },
  {
    id: "pilates-031",
    discipline: "pilates",
    name: "Bridging con brazos extendidos",
    position: "Supino",
    modality: ["mat"],
    level: ["inicial"],
    moment: 2,
    objective: ["lumbopelvica"],
    description: "Con las rodillas flexionadas y los brazos extendidos hacia el techo, elevá la cadera vértebra por vértebra mientras los brazos se mantienen quietos, sosteniendo unos segundos antes de bajar con control.",
    howTo: "Pedí que suban la cadera como si despegaran una vértebra a la vez del piso.",
    adaptation: "Reducir la altura de la elevación de cadera si aparece tensión lumbar.",
    seriesDefault: 3,
  },
  {
    id: "pilates-032",
    discipline: "pilates",
    name: "Mermaid lateral en sedestación",
    position: "Sentada",
    modality: ["mat", "reformer", "mixta"],
    level: ["intermedio"],
    moment: 4,
    objective: ["columna"],
    description: "Sentada con las piernas plegadas a un costado, apoyá una mano en el piso y estirá el otro brazo por encima de la cabeza, alargando el costado del torso sin colapsar el hombro de apoyo.",
    howTo: "Pedí que dejen espacio entre la oreja y el hombro de apoyo; luego repitan del otro lado.",
    adaptation: "Reducir la inclinación lateral o apoyar el antebrazo en lugar de la mano.",
    seriesDefault: 2,
  },
  {
    id: "pilates-033",
    discipline: "pilates",
    name: "Arm Circles con carga liviana en Reformer",
    position: "Sentada de espaldas al cabezal",
    modality: ["reformer", "mixta"],
    level: ["intermedio"],
    moment: 3,
    objective: ["tren-superior"],
    description: "Sentada con carga liviana en los resortes de brazos, dibujá círculos pequeños y controlados hacia adelante manteniendo los hombros alejados de las orejas y el torso erguido durante todo el movimiento.",
    howTo: "Pedí que el círculo salga del hombro, sin que la muñeca se doble para compensar.",
    seriesDefault: 2,
  },
  {
    id: "pilates-034",
    discipline: "pilates",
    name: "Pelvic Clock (reloj pélvico)",
    position: "Supino",
    modality: ["mat"],
    level: ["inicial"],
    moment: 1,
    objective: ["lumbopelvica"],
    description: "Con las rodillas flexionadas, inclina la pelvis suavemente hacia adelante y atrás, y luego hacia los costados, explorando el rango de movimiento antes de volver a la posición neutra.",
    howTo: "Pedí que imaginen un reloj sobre el abdomen y muevan la pelvis apenas hacia cada número.",
    seriesDefault: 1,
  },
  {
    id: "pilates-035",
    discipline: "pilates",
    name: "Standing Leg Press en Reformer",
    position: "De pie sobre la plataforma, manos en la barra",
    modality: ["reformer", "mixta"],
    level: ["intermedio"],
    moment: 3,
    objective: ["centro", "lumbopelvica"],
    avoid: ["Post-cirugía de rodilla"],
    description: "De pie sobre la plataforma con carga media, flexioná y extendé una pierna empujando el carro mientras la pelvis se mantiene estable y el torso erguido durante todo el recorrido.",
    howTo: "Pedí que la cadera no rote hacia el lado que empuja el carro.",
    adaptation: "Reducir el recorrido de la flexión de rodilla o trabajar con carga más liviana.",
    seriesDefault: 3,
  },
  {
    id: "pilates-036",
    discipline: "pilates",
    name: "Side Kick — preparación",
    position: "De costado",
    modality: ["mat"],
    level: ["intermedio"],
    moment: 4,
    objective: ["lumbopelvica"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Apoyada de costado con la cabeza sobre el brazo extendido, elevá la pierna de arriba a la altura de la cadera y llevala hacia adelante y atrás sin que la pelvis rote.",
    howTo: "Pedí que la cadera de arriba se mantenga apilada sobre la de abajo durante todo el recorrido.",
    adaptation: "Reducir la altura de la pierna o acortar el recorrido hacia adelante y atrás.",
    seriesDefault: 2,
  },
  {
    id: "pilates-037",
    discipline: "pilates",
    name: "Teaser — preparación",
    position: "Supino",
    modality: ["mat"],
    level: ["avanzado"],
    moment: 5,
    objective: ["centro", "columna"],
    avoid: ["Hernia de disco lumbar"],
    description: "Con las rodillas en mesa, enrollá el torso hacia arriba mientras extendés las piernas en diagonal, buscando el equilibrio sobre los isquiones con los brazos paralelos al piso.",
    howTo: "Pedí que suban despacio, sintiendo el abdomen antes que la fuerza de las piernas.",
    adaptation: "Mantener las rodillas flexionadas y los pies apoyados en el piso durante la subida.",
    seriesDefault: 2,
  },
  {
    id: "pilates-038",
    discipline: "pilates",
    name: "Reverse Plank apoyada en el carro",
    position: "Sentada en el carro, manos detrás de la cadera",
    modality: ["reformer", "mixta"],
    level: ["avanzado"],
    moment: 5,
    objective: ["tren-superior", "centro"],
    avoid: ["Embarazo / posparto"],
    description: "Sentada con las manos apoyadas detrás y los pies en la barra, elevá la cadera formando una línea recta desde los hombros hasta los talones, sosteniendo unos segundos con el centro activo.",
    howTo: "Pedí que empujen el piso con las manos para que los hombros no se hundan.",
    adaptation: "Mantener la cadera apoyada en el carro y trabajar solo la apertura de pecho.",
    seriesDefault: 2,
  },
  {
    id: "pilates-039",
    discipline: "pilates",
    name: "Roll Over — preparación",
    position: "Supino",
    modality: ["mat"],
    level: ["avanzado"],
    moment: 4,
    objective: ["columna"],
    avoid: ["Hernia de disco lumbar", "Hipermovilidad"],
    description: "Con las piernas extendidas hacia el techo, llevalas por encima de la cabeza con control hasta que la cadera se despega apenas del piso, sosteniendo el movimiento con el centro, no con el impulso.",
    howTo: "Pedí que bajen las piernas más despacio de lo que subieron.",
    adaptation: "Reducir el recorrido llevando las piernas solo hasta la vertical, sin despegar la cadera.",
    seriesDefault: 2,
  },
  {
    id: "pilates-040",
    discipline: "pilates",
    name: "Footwork variado — puntas y talones",
    position: "Supino en el carro",
    modality: ["reformer", "mixta"],
    level: ["inicial"],
    moment: 2,
    objective: ["lumbopelvica"],
    description: "Con los pies en la barra en distintas posiciones (talones, puntas, en V), empujá y regresá el carro con carga liviana, sosteniendo la pelvis neutra en cada variante de apoyo.",
    howTo: "Pedí que noten si algún apoyo les cuesta más mantener la pelvis quieta.",
    seriesDefault: 3,
  },
  {
    id: "pilates-041",
    discipline: "pilates",
    name: "Mermaid completo en Reformer",
    position: "Sentada de costado al carro",
    modality: ["reformer", "mixta"],
    level: ["avanzado"],
    moment: 4,
    objective: ["columna", "tren-superior"],
    description: "Sentada de costado con una mano en la barra y carga liviana, inclina el torso lateralmente empujando el carro con el brazo, alargando la columna antes de volver al centro con control.",
    howTo: "Pedí que alarguen el costado antes de empujar el carro, sin colapsar sobre el brazo de apoyo.",
    seriesDefault: 2,
  },
  {
    id: "pilates-042",
    discipline: "pilates",
    name: "Estiramiento de columna en posición de niño",
    position: "De rodillas",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["columna"],
    avoid: ["Post-cirugía de rodilla"],
    description: "De rodillas, sentate hacia atrás sobre los talones y estirá los brazos hacia adelante apoyando la frente en el piso, alargando la columna mientras respirás hacia la zona media de la espalda.",
    howTo: "Pedí que dirijan la respiración hacia las costillas de la espalda, no solo hacia el pecho.",
    adaptation: "Separar las rodillas o colocar una almohada entre los talones y los glúteos.",
    seriesDefault: 1,
  },
  {
    id: "pilates-043",
    discipline: "pilates",
    name: "Relajación final con escaneo corporal",
    position: "Supino",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["centro"],
    description: "Acostada con las piernas extendidas y los brazos relajados, recorré mentalmente cada zona del cuerpo de los pies a la cabeza, notando dónde quedó tensión y dónde se siente liviano.",
    howTo: "Guiá el recorrido en voz baja y pausada, nombrando cada zona del cuerpo.",
    seriesDefault: 1,
  },
  {
    id: "pilates-044",
    discipline: "pilates",
    name: "Puente con pelota entre las rodillas",
    position: "Supino",
    modality: ["mat"],
    level: ["inicial", "intermedio"],
    moment: 2,
    objective: ["lumbopelvica"],
    avoid: ["Disfunción de suelo pélvico"],
    description: "Con una pelota pequeña entre las rodillas y los pies apoyados, elevá la cadera mientras sostenés una presión suave y constante sobre la pelota, coordinando la respiración con el movimiento.",
    howTo: "Pedí una presión suave y sostenida sobre la pelota, no un apriete máximo.",
    adaptation: "Realizar solo la activación con la pelota, sin elevar la cadera, si hay antecedentes de tensión pélvica.",
    seriesDefault: 2,
  },
  {
    id: "yoga-021",
    discipline: "yoga",
    name: "Postura de la montaña con activación de pies (Tadasana)",
    position: "De pie",
    modality: ["suave"],
    level: ["inicial"],
    moment: 1,
    objective: ["enraizamiento"],
    description: "De pie con los pies al ancho de cadera, repartí el peso entre los cuatro puntos de apoyo del pie y sentí cómo la postura se organiza desde el piso hacia arriba.",
    howTo: "Pedí que noten si el peso cae más hacia los talones o hacia los dedos, y busquen el centro.",
    seriesDefault: 1,
  },
  {
    id: "yoga-022",
    discipline: "yoga",
    name: "Flexión lateral de pie",
    position: "De pie",
    modality: ["suave", "dinamico"],
    level: ["intermedio"],
    moment: 2,
    objective: ["columna-yoga"],
    description: "De pie con los pies juntos, elevá un brazo y flexioná el torso hacia el lado contrario, alargando la cintura antes de inclinarte, y volvé al centro con control.",
    howTo: "Pedí que crezcan con la inhalación antes de inclinarse hacia el costado; luego repitan del otro lado.",
    adaptation: "Reducir la inclinación lateral o apoyar la mano libre en la cadera.",
    seriesDefault: 1,
  },
  {
    id: "yoga-023",
    discipline: "yoga",
    name: "Guerrero III con apoyo (Virabhadrasana III modificada)",
    position: "De pie",
    modality: ["dinamico"],
    level: ["avanzado"],
    moment: 4,
    objective: ["fuerza-yoga", "cadera"],
    description: "Desde una pierna, inclina el torso hacia adelante mientras la otra pierna se extiende hacia atrás, buscando una línea recta desde la cabeza hasta el talón, sosteniendo el equilibrio con la mirada fija.",
    howTo: "Pedí que estiren la pierna de atrás como si empujaran una pared invisible con el talón.",
    adaptation: "Mantener las manos apoyadas en un bloque o silla al frente para sostener el equilibrio.",
    seriesDefault: 1,
  },
  {
    id: "yoga-024",
    discipline: "yoga",
    name: "Postura del árbol (Vrksasana)",
    position: "De pie",
    modality: ["suave", "dinamico"],
    level: ["inicial", "intermedio"],
    moment: 2,
    objective: ["enraizamiento"],
    description: "De pie sobre una pierna, apoyá la planta del otro pie en la pantorrilla o el muslo, evitando la rodilla, y juntá las manos al frente del pecho sosteniendo la mirada en un punto fijo.",
    howTo: "Pedí que fijen la mirada antes de levantar el pie del piso.",
    adaptation: "Apoyar apenas la punta del pie en el piso junto al tobillo de la pierna de base.",
    seriesDefault: 1,
  },
  {
    id: "yoga-025",
    discipline: "yoga",
    name: "Paloma con apoyo de bloque (Eka Pada Rajakapotasana modificada)",
    position: "Sentada",
    modality: ["dinamico"],
    level: ["intermedio"],
    moment: 4,
    objective: ["cadera"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Con una pierna flexionada al frente y la otra extendida hacia atrás, apoyá un bloque debajo del glúteo de la pierna flexionada si la cadera no llega cómoda al piso, y respirá sosteniendo la postura.",
    howTo: "Pedí que ajusten la altura del bloque hasta sentir la cadera estable, sin dolor agudo.",
    adaptation: "Realizar la variante reclinada con la pierna en cuatro, en lugar de la versión sentada.",
    seriesDefault: 1,
  },
  {
    id: "yoga-026",
    discipline: "yoga",
    name: "Postura del niño (Balasana)",
    position: "De rodillas",
    modality: ["restaurativo", "suave"],
    level: ["inicial"],
    moment: 1,
    objective: ["columna-yoga"],
    avoid: ["Embarazo / posparto"],
    description: "De rodillas, sentate hacia atrás sobre los talones y estirá los brazos hacia adelante o dejalos al costado del cuerpo, apoyando la frente en el piso y respirando con calma.",
    howTo: "Pedí que sientan el peso del cuerpo entregado por completo al piso en cada exhalación.",
    adaptation: "Separar las rodillas para dejar espacio al abdomen, o apoyar un almohadón bajo el torso.",
    seriesDefault: 1,
  },
  {
    id: "yoga-027",
    discipline: "yoga",
    name: "Plancha invertida sentada (Purvottanasana modificada)",
    position: "Sentada",
    modality: ["dinamico"],
    level: ["avanzado"],
    moment: 4,
    objective: ["fuerza-yoga"],
    avoid: ["Hernia de disco lumbar"],
    description: "Sentada con las manos apoyadas detrás de la cadera y los dedos apuntando hacia adelante, elevá la cadera formando una línea desde los hombros hasta los talones, sosteniendo con el centro activo.",
    howTo: "Pedí que empujen el piso con las manos para que los hombros no se hundan hacia las orejas.",
    adaptation: "Mantener la cadera apoyada en el piso y trabajar solo la apertura del pecho.",
    seriesDefault: 1,
  },
  {
    id: "yoga-028",
    discipline: "yoga",
    name: "Postura del puente (Setu Bandha Sarvangasana)",
    position: "Supino",
    modality: ["dinamico", "suave"],
    level: ["intermedio"],
    moment: 3,
    objective: ["fuerza-yoga", "columna-yoga"],
    description: "Con las rodillas flexionadas y los pies apoyados, elevá la cadera hacia el techo mientras las manos se entrelazan debajo del cuerpo, sosteniendo la postura con la