/* ============================================================
   BASE DE DATOS DE EJERCICIOS
   ------------------------------------------------------------
   Cada ejercicio tiene esta forma:

   {
     id: string único
     discipline: "pilates" | "yoga"
     name: string
     position: string (texto libre, ej "Supino", "De pie")
     modality: ["mat","reformer"] o ["suave","dinamico","restaurativo"]
     level: ["inicial","intermedio","avanzado"]
     moment: 1 a 6  -> a qué bloque de la clase pertenece
     objective: ["id-de-objetivo", ...]
     avoid: ["tag-contraindicacion", ...]  (opcional)
     description: texto que ve la alumna/instructora
     howTo: cómo explicarlo (opcional)
     adaptation: adaptación por patología (opcional, texto orientativo)
     seriesDefault: número de series sugeridas
   }
   ============================================================ */

const BLOCKS = [
  { id: 1, name: "Preparar el Cuerpo",              subtitle: "Llevar la atención al cuerpo, activar la respiración",        weight: 0.15, optional: true },
  { id: 2, name: "Activar el Centro",               subtitle: "Despertar el centro, sentar las bases",                       weight: 0.17 },
  { id: 3, name: "Construir el Patrón Principal",   subtitle: "El patrón central, ligado al objetivo elegido",               weight: 0.22 },
  { id: 4, name: "Desafiar sin Desordenar",         subtitle: "Variación, carga o coordinación sobre lo aprendido",          weight: 0.17 },
  { id: 5, name: "Integrar en Movimiento Global",   subtitle: "Secuencia fluida que une lo trabajado",                       weight: 0.14 },
  { id: 6, name: "Cerrar con Conciencia",           subtitle: "Vuelta al eje, respiración, sensación final",                 weight: 0.15 },
];

const OBJECTIVES = {
  pilates: [
    { id: "lumbopelvica", label: "Estabilidad Lumbopélvica" },
    { id: "columna", label: "Movilidad de Columna" },
    { id: "tren-superior", label: "Fuerza de Tren Superior" },
    { id: "centro", label: "Conexión con el Centro" },
    { id: "control-escapular", label: "Control Escapular" },
    { id: "coordinacion-fluidez", label: "Coordinación y Fluidez" },
  ],
  yoga: [
    { id: "enraizamiento", label: "Equilibrio y Enraizamiento" },
    { id: "cadera", label: "Apertura de Cadera" },
    { id: "columna-yoga", label: "Flexibilidad de Columna" },
    { id: "fuerza-yoga", label: "Fuerza y Estabilidad" },
  ],
};

const MODALITIES = {
  pilates: [
    { id: "mat", label: "Mat" },
    { id: "reformer", label: "Reformer" },
    { id: "mixta", label: "Mixta" },
  ],
  yoga: [
    { id: "suave", label: "Suave" },
    { id: "dinamico", label: "Dinámico" },
    { id: "restaurativo", label: "Restaurativo" },
  ],
};

const POPULATIONS = [
  { id: "general", label: "Adultos (general)" },
  { id: "mayores", label: "Adultos mayores" },
  { id: "embarazo", label: "Embarazo / posparto" },
  { id: "principiantes", label: "Principiantes absolutas" },
];

const AVOID_TAGS = [
  "Osteoporosis / osteopenia",
  "Hernia de disco lumbar",
  "Embarazo / posparto",
  "Problemas de cadera / prótesis",
  "Post-cirugía de rodilla",
  "Hipermovilidad",
  "Fibromialgia",
  "Disfunción de suelo pélvico",
];

const EXERCISES = [
  {
    id: "pilates-001",
    discipline: "pilates",
    name: "Respiración lateral en cuadrupedia",
    position: "Cuadrupedia",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 1,
    objective: ["centro", "adultos-mayores", "principiantes-abs", "miedo-movimiento"],
    description: "Apoyada en manos y rodillas, dirigí el aire hacia las costillas laterales al inhalar y sentí cómo se estrechan al exhalar, activando el centro antes de empezar a moverte.",
    howTo: "Pedí que sientan que las costillas se abren como un acordeón hacia los costados.",
    adaptation: "Si las muñecas molestan, apoyar los antebrazos en el piso en lugar de las manos.",
    coaching: {
      verbal: "Guiá con calma: inhalá abriendo las costillas hacia los costados, exhalá cerrando suavemente sin hundir la espalda.",
      imagenMental: "Las costillas son como las varillas de un abanico que se abre a los lados con el aire.",
      tactil: "Apoyá tus manos, con permiso, a los costados de las costillas de la alumna para que sienta hacia dónde tiene que expandir.",
      pregunta: "¿Sentís que el aire llega más a los costados que hacia arriba, al pecho?",
    },
    progression: "en cuadrupedia ya es una base accesible para cualquier nivel; para progresar, sumá conciencia de la espalda baja durante la inhalación",
    adaptations: {
      "Embarazo / posparto": "Apoyar manos y rodillas separadas al ancho de cadera y dejar espacio para el abdomen; reducir el tiempo de sostén si aparece fatiga.",
      "Problemas de cadera / prótesis": "Colocar una manta doblada debajo de las rodillas para reducir la presión en la cadera de apoyo.",
    },
    seriesDefault: 1,
  },
  {
    id: "pilates-002",
    discipline: "pilates",
    name: "Rodar hacia abajo (Roll Down)",
    position: "De pie",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 1,
    objective: ["columna", "adultos-mayores", "principiantes-abs"],
    avoid: ["Hipermovilidad"],
    description: "De pie, dejá caer la cabeza y desenrollá la columna vértebra por vértebra hacia el piso, soltando cuello y hombros, y luego subí enrollando desde la base.",
    howTo: "Contá las vértebras en voz baja mientras bajan, como si fueran cuentas de un collar.",
    adaptation: "Flexionar las rodillas si los isquiotibiales están tensos o si aparece molestia lumbar.",
    coaching: {
      verbal: "Pedí que dejen caer la cabeza primero, después los hombros, y recién ahí empiecen a desenrollar el resto de la columna.",
      imagenMental: "La columna se despliega como una cortina que baja despacio, vértebra por vértebra.",
      tactil: "Apoyá una mano suavemente sobre la zona media de la espalda para marcar el punto por donde sigue el desenrollado.",
      pregunta: "¿Podés sentir cada vértebra por separado, o baja todo el torso de un solo bloque?",
    },
    progression: "sostené el ritmo lento en todos los niveles; para progresar, sumá una pausa de dos respiraciones a mitad de camino",
    adaptations: {
      "Hipermovilidad": "Pedir que no busquen el rango máximo hacia abajo: frenar el descenso antes del punto de mayor flexión y sostener con el abdomen activo.",
      "Osteoporosis / osteopenia": "Evitar la flexión completa de columna; limitar el recorrido a una inclinación suave manteniendo la espalda más neutra.",
    },
    seriesDefault: 2,
  },
  {
    id: "pilates-003",
    discipline: "pilates",
    name: "Pies en la barra — activación de neutro",
    position: "Supino en el carro",
    modality: ["reformer", "mixta"],
    level: ["inicial", "intermedio"],
    moment: 1,
    objective: ["lumbopelvica"],
    description: "Con los pies apoyados en la barra y carga liviana, encontrá la posición neutra de la pelvis y sostenela mientras el carro se desliza apenas, sin perder el apoyo lumbar.",
    howTo: "Pedí que noten si la zona lumbar se despega del carro al moverse.",
    seriesDefault: 2,
  },
  {
    id: "pilates-004",
    discipline: "pilates",
    name: "The Hundred — preparación",
    position: "Supino",
    modality: ["mat"],
    level: ["inicial", "intermedio"],
    moment: 2,
    objective: ["centro"],
    description: "Con las rodillas en mesa y la cabeza apoyada, bombeá los brazos suavemente al costado del cuerpo mientras sostenés la respiración en cinco tiempos, activando el centro sin tensar el cuello.",
    howTo: "Si el cuello tensa, pedí que apoyen la cabeza y trabajen solo con los brazos.",
    adaptation: "Mantener la cabeza apoyada en el piso durante toda la serie si el cuello se fatiga.",
    coaching: {
      verbal: "Pedí que mantengan la cabeza apoyada y bombeen los brazos parejo, sin que se acelere la respiración.",
      imagenMental: "Los brazos golpean el aire como si estuvieran chapoteando agua, livianos y parejos.",
      tactil: "Apoyá dos dedos sobre el abdomen bajo para que sienta que se mantiene firme mientras los brazos se mueven.",
      pregunta: "¿El abdomen se mantiene firme o se abulta cuando bombeás los brazos?",
    },
    progression: "con la cabeza apoyada es la entrada a este patrón; para progresar hacia niveles más avanzados, se suma el enrollado del torso",
    adaptations: {
      "Disfunción de suelo pélvico": "Coordinar el bombeo de brazos con una exhalación suave y sostenida, sin retener el aire ni empujar hacia abajo.",
      "Hernia de disco lumbar": "Mantener ambas rodillas apoyadas en el piso en lugar de en mesa, para reducir la exigencia sobre la zona lumbar.",
    },
    seriesDefault: 1,
  },
  {
    id: "pilates-005",
    discipline: "pilates",
    name: "Push Through Bar — remo sentado",
    position: "Sentada en el carro",
    modality: ["reformer", "mixta"],
    level: ["intermedio", "avanzado"],
    moment: 2,
    objective: ["tren-superior"],
    description: "Sentada de espaldas al cabezal, empujá la barra hacia adelante y abajo con carga liviana, organizando primero las escápulas y luego extendiendo los codos con control.",
    howTo: "Pedí que bajen los omóplatos antes de que las manos se muevan un centímetro.",
    coaching: {
      verbal: "Pedí que bajen y atrás los omóplatos antes de que las manos empiecen a moverse.",
      imagenMental: "Los omóplatos se deslizan hacia los bolsillos traseros del pantalón antes de que se muevan los brazos.",
      tactil: "Apoyá una mano sobre el omóplato para que sienta el punto exacto donde tiene que anclar antes de tirar de la barra.",
      pregunta: "¿Sentís que el movimiento arranca desde la espalda o desde los brazos?",
    },
    progression: "con carga liviana alcanza para organizar el patrón; progresá aumentando levemente la resistencia una vez que el control escapular es estable",
    adaptations: {
      "Problemas de cadera / prótesis": "Sentarse sobre un cojín o step para elevar levemente la cadera y aliviar la flexión de cadera al estar sentada.",
    },
    seriesDefault: 3,
  },
  {
    id: "pilates-006",
    discipline: "pilates",
    name: "Rotación de columna sentada (Spine Twist)",
    position: "Sentada",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 2,
    objective: ["columna"],
    avoid: ["Hernia de disco lumbar"],
    description: "Sentada con piernas extendidas y brazos abiertos, rotá el torso hacia un lado en dos pulsos breves manteniendo la pelvis fija, y volvé al centro con control.",
    howTo: "La pelvis no gira con el torso: si se mueve, achicá el recorrido de la rotación.",
    adaptation: "Reducir el rango de rotación o realizarla con las rodillas flexionadas y apoyadas.",
    seriesDefault: 3,
  },
  {
    id: "pilates-007",
    discipline: "pilates",
    name: "Single Leg Stretch — preparación",
    position: "Supino",
    modality: ["mat"],
    level: ["inicial", "intermedio"],
    moment: 3,
    objective: ["lumbopelvica", "centro"],
    description: "Con una rodilla al pecho y la otra pierna extendida en el aire, sostené el torso estable mientras alternás las piernas de forma lenta y controlada.",
    howTo: "Pedí que mantengan la zona lumbar apoyada, sin que se despegue al cambiar de pierna.",
    adaptation: "Apoyar la cabeza en el piso y mantener ambas rodillas flexionadas si el cuello o el abdomen se fatigan.",
    coaching: {
      verbal: "Pedí que mantengan la zona lumbar apoyada mientras alternan las piernas, sin acelerar el ritmo.",
      imagenMental: "Las piernas se turnan como si estuvieran pedaleando una bicicleta muy lenta y controlada.",
      tactil: "Apoyá dos dedos debajo de la zona lumbar para que sienta si se despega al cambiar de pierna.",
      pregunta: "¿La zona lumbar se mantiene en contacto con el piso todo el tiempo, o se despega en algún cambio?",
    },
    progression: "con la cabeza apoyada y ritmo lento es la base; progresá sumando el enrollado del torso cuando el control lumbar sea sólido",
    adaptations: {
      "Hernia de disco lumbar": "Reducir la altura de la pierna extendida y acortar el recorrido, priorizando que la zona lumbar no se despegue del piso.",
      "Embarazo / posparto": "Trabajar con movimientos más pequeños y controlados, evitando la presión abdominal excesiva; suspender si genera molestia.",
    },
    seriesDefault: 3,
  },
  {
    id: "pilates-008",
    discipline: "pilates",
    name: "Elephant (perro que camina en el carro)",
    position: "De pie en el carro, manos en la barra",
    modality: ["reformer", "mixta"],
    level: ["intermedio", "avanzado"],
    moment: 3,
    objective: ["centro", "lumbopelvica"],
    description: "Con las manos en la barra y los talones apoyados en la plataforma, empujá el carro alejando la cadera hacia atrás mientras mantenés la columna larga y el centro conectado.",
    howTo: "Pedí que alejen más la cadera de las manos que las manos de los pies.",
    adaptation: "Trabajar con las rodillas ligeramente flexionadas si los isquiotibiales están muy tensos.",
    seriesDefault: 3,
  },
  {
    id: "pilates-009",
    discipline: "pilates",
    name: "The Hundred (completo)",
    position: "Supino",
    modality: ["mat"],
    level: ["intermedio", "avanzado"],
    moment: 3,
    objective: ["centro", "columna"],
    avoid: ["Hernia de disco lumbar"],
    description: "Con el torso enrollado y las piernas extendidas en diagonal, bombeá los brazos con energía sosteniendo el abdomen conectado y el cuello relajado durante toda la serie de respiraciones.",
    howTo: "Si el cuello se tensa, pedí que bajen la cabeza y sigan solo con las piernas.",
    adaptation: "Mantener las rodillas flexionadas en mesa y la cabeza apoyada para reducir la exigencia abdominal y cervical.",
    coaching: {
      verbal: "Pedí que mantengan el cuello relajado y el abdomen conectado durante las cien respiraciones.",
      imagenMental: "Los brazos laten como el aleteo rápido y chico de un colibrí, sin perder el eje del torso.",
      tactil: "Apoyá una mano bajo la nuca para chequear que no haya tensión excesiva mientras sostiene el enrollado.",
      pregunta: "¿Podés sostener el enrollado del torso sin que el cuello empiece a cargarse?",
    },
    progression: "el enrollado completo con piernas en diagonal es para niveles intermedio/avanzado; para progresar, extendé más las piernas manteniendo el mismo control abdominal",
    adaptations: {
      "Hernia de disco lumbar": "Mantener las rodillas flexionadas en mesa y la cabeza apoyada en el piso durante toda la serie, sin enrollar el torso.",
      "Embarazo / posparto": "Reemplazar por la versión con cabeza apoyada y sin enrollado de torso, priorizando la respiración y el bombeo de brazos.",
    },
    seriesDefault: 1,
  },
  {
    id: "pilates-010",
    discipline: "pilates",
    name: "Chest Expansion (expansión de pecho)",
    position: "De rodillas en el carro",
    modality: ["reformer", "mixta"],
    level: ["intermedio", "avanzado"],
    moment: 3,
    objective: ["tren-superior", "columna"],
    description: "Arrodillada de espaldas al cabezal, tirá de las correas hacia atrás mientras la columna se mantiene larga, y girá la cabeza hacia cada lado antes de volver al centro.",
    howTo: "Pedí que el movimiento salga de los hombros hacia atrás, no de arquear la espalda.",
    seriesDefault: 3,
  },
  {
    id: "pilates-011",
    discipline: "pilates",
    name: "Single Leg Circles",
    position: "Supino",
    modality: ["mat"],
    level: ["intermedio"],
    moment: 4,
    objective: ["lumbopelvica"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Con una pierna extendida hacia el techo, dibujá círculos amplios y controlados mientras la pelvis permanece completamente quieta; luego repetí la misma cantidad con la otra pierna.",
    howTo: "Si la pelvis se balancea, pedí que achiquen el círculo hasta recuperar el control.",
    adaptation: "Flexionar levemente la rodilla de la pierna que se mueve para reducir la palanca.",
    coaching: {
      verbal: "Pedí que dibujen círculos amplios solo mientras la pelvis se mantiene absolutamente quieta.",
      imagenMental: "La pierna dibuja el borde de un plato imaginario en el aire, sin que la pelvis se entere.",
      tactil: "Apoyá las manos sobre ambos lados de la pelvis para que sienta si se balancea con el círculo.",
      pregunta: "¿En qué parte del círculo sentís que la pelvis empieza a moverse?",
    },
    progression: "con la rodilla algo flexionada se reduce la palanca; progresá extendiendo más la pierna a medida que el control mejora",
    adaptations: {
      "Problemas de cadera / prótesis": "Reducir mucho el tamaño del círculo y trabajar dentro de un rango cómodo, sin cruzar la línea media del cuerpo.",
      "Hipermovilidad": "Evitar buscar el rango máximo del círculo; priorizar el control muscular sobre la amplitud del movimiento.",
    },
    seriesDefault: 3,
  },
  {
    id: "pilates-012",
    discipline: "pilates",
    name: "Triceps Press (elbows into springs)",
    position: "Sentada de espaldas al cabezal",
    modality: ["reformer", "mixta"],
    level: ["intermedio", "avanzado"],
    moment: 4,
    objective: ["tren-superior"],
    description: "Con los codos apoyados en el cabezal y carga liviana, extendé los antebrazos hacia atrás sin mover los hombros, sosteniendo el torso erguido y el centro activo.",
    howTo: "Pedí que los codos queden fijos como bisagras: solo se mueve el antebrazo.",
    seriesDefault: 3,
  },
  {
    id: "pilates-013",
    discipline: "pilates",
    name: "Saw (Sierra)",
    position: "Sentada, piernas abiertas",
    modality: ["mat"],
    level: ["intermedio", "avanzado"],
    moment: 4,
    objective: ["columna", "centro"],
    avoid: ["Hernia de disco lumbar"],
    description: "Sentada con las piernas abiertas, rotá el torso hacia un lado y estirá el brazo opuesto hacia el pie como serruchando, manteniendo ambos isquiones apoyados en el piso.",
    howTo: "Pedí que ambos isquiones se mantengan apoyados durante toda la rotación hacia los dos lados.",
    adaptation: "Reducir la flexión hacia adelante y mantener la columna más erguida durante la rotación.",
    coaching: {
      verbal: "Pedí que ambos isquiones se mantengan apoyados mientras el torso rota hacia cada lado.",
      imagenMental: "El brazo serrucha el aire hacia el pie de adelante, como si cortara con un serrucho imaginario.",
      tactil: "Apoyá una mano sobre el isquion que tiende a despegarse para que la alumna registre dónde sostener el peso.",
      pregunta: "¿Sentís que un lado de la cadera se levanta más que el otro al rotar?",
    },
    progression: "mantener la columna más erguida y rotar menos es la entrada; progresá aumentando el rango de flexión hacia adelante en cada rotación",
    adaptations: {
      "Hernia de disco lumbar": "Reducir la flexión hacia adelante y priorizar la rotación con la columna erguida, sin buscar tocar el pie.",
      "Osteoporosis / osteopenia": "Evitar la flexión combinada con rotación completa; trabajar solo la rotación de torso manteniendo la columna neutra.",
    },
    seriesDefault: 3,
  },
  {
    id: "pilates-014",
    discipline: "pilates",
    name: "Knee Stretch redondo",
    position: "Cuadrupedia sobre el carro",
    modality: ["reformer", "mixta"],
    level: ["intermedio", "avanzado"],
    moment: 4,
    objective: ["centro"],
    avoid: ["Post-cirugía de rodilla"],
    description: "Con las rodillas sobre la plataforma y las manos en la barra, redondeá la columna y alejá el carro empujando desde el centro, sin perder la curva de la espalda.",
    howTo: "Pedí que imaginen que abrazan una pelota grande con el abdomen durante todo el movimiento.",
    seriesDefault: 3,
  },
  {
    id: "pilates-015",
    discipline: "pilates",
    name: "Swimming (Natación)",
    position: "Prono",
    modality: ["mat"],
    level: ["intermedio", "avanzado"],
    moment: 5,
    objective: ["centro", "columna"],
    avoid: ["Embarazo / posparto"],
    description: "Boca abajo con brazos y piernas extendidos, elevá levemente brazo y pierna opuestos alternando en un ritmo continuo, como si nadaras, sosteniendo el centro activo todo el tiempo.",
    howTo: "Pedí un movimiento chico y rápido, sin que la zona lumbar se comprima.",
    adaptation: "Reducir la altura de brazos y piernas o trabajar de a un lado por vez.",
    coaching: {
      verbal: "Pedí un movimiento chico y rápido de brazo y pierna opuestos, sin que la zona lumbar se comprima.",
      imagenMental: "El cuerpo se mueve como si nadara en aguas muy poco profundas, con movimientos cortos y parejos.",
      tactil: "Apoyá una mano suavemente sobre la zona lumbar para que sienta si se comprime al elevar brazo y pierna.",
      pregunta: "¿La zona lumbar se siente comprimida o se mantiene larga durante el movimiento?",
    },
    progression: "con movimientos de menor amplitud es más accesible; progresá aumentando la altura de brazo y pierna manteniendo la zona lumbar larga",
    adaptations: {
      "Embarazo / posparto": "Evitar la posición prona; reemplazar por cuadrupedia, elevando brazo y pierna opuestos con el mismo patrón.",
      "Disfunción de suelo pélvico": "Coordinar el movimiento con una exhalación activa, evitando retener el aire durante las elevaciones.",
    },
    seriesDefault: 2,
  },
  {
    id: "pilates-016",
    discipline: "pilates",
    name: "Long Stretch (plancha en el carro)",
    position: "De pie, manos en la barra, carro móvil",
    modality: ["reformer", "mixta"],
    level: ["avanzado"],
    moment: 5,
    objective: ["centro", "tren-superior"],
    avoid: ["Embarazo / posparto", "Disfunción de suelo pélvico"],
    description: "En posición de plancha con las manos en la barra, empujá el carro alejándolo con las piernas mientras el cuerpo se mantiene en una línea recta de cabeza a talones.",
    howTo: "Pedí que la cadera no suba ni baje: la línea del cuerpo se mantiene entera.",
    adaptation: "Realizar el movimiento con las rodillas apoyadas en la plataforma en lugar de en plancha completa.",
    coaching: {
      verbal: "Pedí que la línea de cabeza a talones se mantenga entera mientras el carro se aleja y regresa.",
      imagenMental: "El cuerpo es una tabla rígida que se desliza entera, sin que ninguna parte se adelante o se atrase.",
      tactil: "Apoyá una mano sobre la zona lumbar para chequear que no se hunda mientras el carro se aleja.",
      pregunta: "¿La cadera se mantiene alineada con los hombros y los talones, o sube o baja en algún punto?",
    },
    progression: "es un ejercicio de nivel avanzado; para acercarse a él antes de dominarlo, practicá el mismo patrón con las rodillas apoyadas en la plataforma",
    adaptations: {
      "Embarazo / posparto": "Evitar por completo la posición de plancha; trabajar el mismo patrón de empuje con las rodillas apoyadas y menor carga.",
      "Disfunción de suelo pélvico": "Reducir la distancia que recorre el carro y coordinar el esfuerzo con la exhalación, sin retener el aire.",
      "Hipermovilidad": "Evitar bloquear los codos; mantenerlos con una leve flexión activa durante todo el recorrido.",
    },
    seriesDefault: 3,
  },
  {
    id: "pilates-017",
    discipline: "pilates",
    name: "Push-up modificado sobre rodillas",
    position: "Cuadrupedia",
    modality: ["mat", "reformer", "mixta"],
    level: ["intermedio", "avanzado"],
    moment: 5,
    objective: ["tren-superior", "centro"],
    description: "Con las rodillas apoyadas y las manos debajo de los hombros, flexioná los codos hacia atrás bajando el pecho con control, manteniendo la columna larga durante todo el recorrido.",
    howTo: "Pedí que los codos se deslicen hacia atrás, cerca de las costillas, no hacia afuera.",
    seriesDefault: 3,
  },
  {
    id: "pilates-018",
    discipline: "pilates",
    name: "Postura de descanso (Rest Position)",
    position: "De rodillas",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["columna", "adultos-mayores", "miedo-movimiento"],
    avoid: ["Post-cirugía de rodilla"],
    description: "Sentate hacia atrás sobre los talones con los brazos extendidos al frente, soltando el peso de la espalda y respirando hacia la zona lumbar durante unas respiraciones.",
    howTo: "Pedí que sientan cómo se separan las vértebras con cada exhalación.",
    adaptation: "Colocar una almohada entre los talones y los glúteos si hay molestia en rodillas o tobillos.",
    coaching: {
      verbal: "Pedí que suelten el peso de la espalda hacia atrás, sin sostener tensión en los brazos.",
      imagenMental: "La espalda se estira como una banda elástica que se suelta después de todo el trabajo de la clase.",
      tactil: "Apoyá una mano suave sobre el sacro para invitar a que el peso caiga hacia los talones.",
      pregunta: "¿Sentís que la respiración llega hasta la espalda baja en esta posición?",
    },
    progression: "es una postura de cierre válida para todos los niveles; no requiere progresión, solo ajustar el tiempo de permanencia según la energía del grupo",
    adaptations: {
      "Post-cirugía de rodilla": "Colocar una almohada entre los talones y los glúteos, o realizar la variante sentada con las piernas extendidas hacia adelante.",
      "Embarazo / posparto": "Separar más las rodillas para dejar espacio al abdomen, o reemplazar por una posición sentada con torso apoyado en una almohada.",
    },
    seriesDefault: 1,
  },
  {
    id: "pilates-019",
    discipline: "pilates",
    name: "Respiración final en neutro",
    position: "Supino",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["centro", "lumbopelvica", "principiantes-abs", "miedo-movimiento"],
    description: "Acostada con las rodillas flexionadas, volvé a la columna neutra del comienzo y notá los cambios en el apoyo, la respiración y la tensión general del cuerpo.",
    howTo: "Invitá a comparar en silencio cómo se siente el cuerpo ahora respecto al inicio de la clase.",
    coaching: {
      verbal: "Invitá a comparar en silencio cómo se siente el cuerpo ahora respecto al inicio de la clase.",
      imagenMental: "El cuerpo vuelve al mismo punto de partida, pero ahora con más información sobre sí mismo.",
      tactil: "No hace falta contacto físico en este cierre; dejá que la alumna registre las sensaciones por su cuenta.",
      pregunta: "¿Qué cambió entre la respiración del comienzo y esta, ahora?",
    },
    progression: "es un cierre apto para todos los niveles, sin necesidad de progresión",
    seriesDefault: 1,
  },
  {
    id: "pilates-020",
    discipline: "pilates",
    name: "Estiramiento cruzado de cadera en supino",
    position: "Supino",
    modality: ["mat"],
    level: ["inicial", "intermedio"],
    moment: 6,
    objective: ["lumbopelvica", "adultos-mayores"],
    avoid: ["Hernia de disco lumbar"],
    description: "Con las rodillas flexionadas, dejá caer ambas piernas juntas hacia un costado sosteniendo los hombros apoyados en el piso, estirando suavemente la zona lumbar y la cadera.",
    howTo: "Pedí que los hombros no se despeguen del piso; luego repetí llevando las piernas hacia el otro costado.",
    adaptation: "Reducir el recorrido del descenso de las piernas o colocar una almohada de apoyo entre las rodillas.",
    seriesDefault: 1,
  },
  {
    id: "pilates-021",
    discipline: "pilates",
    name: "Protracción y retracción escapular en cuadrupedia",
    position: "Cuadrupedia",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio"],
    moment: 1,
    objective: ["control-escapular"],
    description: "Apoyada en manos y rodillas, dejá que el pecho caiga levemente entre los omóplatos y luego empujá el piso alejándolo, moviendo solo la escápula sin flexionar los codos.",
    howTo: "Pedí que sientan que el espacio entre los omóplatos se ensancha al empujar el piso.",
    adaptation: "Reducir el recorrido del movimiento si aparece molestia en la muñeca de apoyo.",
    seriesDefault: 2,
  },
  {
    id: "pilates-022",
    discipline: "pilates",
    name: "Reloj escapular con brazos elevados",
    position: "Supino",
    modality: ["mat"],
    level: ["intermedio"],
    moment: 2,
    objective: ["control-escapular", "tren-superior"],
    description: "Con los brazos extendidos hacia el techo, deslizá los omóplatos hacia arriba, abajo y a los costados sin mover los brazos del punto fijo, como si dibujaran un reloj sobre la colchoneta.",
    howTo: "Pedí que localicen el movimiento solo en la espalda, no en los brazos ni el cuello.",
    seriesDefault: 2,
  },
  {
    id: "pilates-023",
    discipline: "pilates",
    name: "Arm Springs — remo con control escapular",
    position: "Sentada de espaldas al cabezal",
    modality: ["reformer", "mixta"],
    level: ["intermedio", "avanzado"],
    moment: 3,
    objective: ["control-escapular", "tren-superior"],
    description: "Sentada con carga liviana en los resortes de brazos, tirá hacia atrás organizando primero el omóplato hacia abajo y luego extendiendo el codo, sosteniendo el torso estable durante todo el recorrido.",
    howTo: "Pedí que bajen el omóplato antes de que la mano se mueva, como si lo guardaran en el bolsillo trasero.",
    seriesDefault: 3,
  },
  {
    id: "pilates-024",
    discipline: "pilates",
    name: "Deslizamiento de brazos en pared (Wall Slides)",
    position: "De pie, espalda apoyada en la pared",
    modality: ["mat"],
    level: ["inicial"],
    moment: 1,
    objective: ["control-escapular", "columna", "miedo-movimiento"],
    description: "De espaldas contra la pared, deslizá los brazos hacia arriba y abajo manteniendo el contacto de la zona lumbar y los omóplatos, sin que las costillas se levanten al subir los brazos.",
    howTo: "Pedí que noten si la zona lumbar se despega de la pared al subir los brazos.",
    adaptation: "Reducir la altura del recorrido de los brazos si no logran mantener el apoyo lumbar.",
    seriesDefault: 2,
  },
  {
    id: "pilates-025",
    discipline: "pilates",
    name: "Plancha alta con foco en omóplatos",
    position: "Prono, apoyo en manos y pies",
    modality: ["mat", "reformer", "mixta"],
    level: ["avanzado"],
    moment: 4,
    objective: ["control-escapular", "centro"],
    avoid: ["Embarazo / posparto"],
    description: "En posición de plancha alta, dejá que el pecho caiga apenas entre los omóplatos y luego empujá el piso para separarlos, sosteniendo la línea del cuerpo firme durante el movimiento.",
    howTo: "Pedí que el movimiento sea chico: solo la caja torácica sube y baja entre los brazos.",
    adaptation: "Realizar el movimiento con las rodillas apoyadas en el piso en lugar de en plancha completa.",
    seriesDefault: 2,
  },
  {
    id: "pilates-026",
    discipline: "pilates",
    name: "Roll Up con brazos alternados",
    position: "Supino",
    modality: ["mat"],
    level: ["intermedio"],
    moment: 3,
    objective: ["coordinacion-fluidez", "columna"],
    description: "Enrollá la columna hacia arriba llevando un brazo al frente y el otro hacia atrás, alternando el lado en cada repetición mientras el torso sube y baja con control.",
    howTo: "Pedí que decidan qué brazo va adelante antes de empezar a subir, para no perder el ritmo.",
    adaptation: "Flexionar las rodillas y usar el impulso de los brazos si la zona lumbar tensa al subir.",
    seriesDefault: 2,
  },
  {
    id: "pilates-027",
    discipline: "pilates",
    name: "Footwork con cambio de ritmo en Reformer",
    position: "Supino en el carro",
    modality: ["reformer", "mixta"],
    level: ["intermedio"],
    moment: 2,
    objective: ["coordinacion-fluidez", "lumbopelvica"],
    description: "Con los pies en la barra y carga media, alterná dos empujes rápidos y uno lento en cada serie, sosteniendo la pelvis neutra mientras cambia el ritmo del movimiento.",
    howTo: "Pedí que cuenten en voz alta el patrón rápido-rápido-lento antes de empezar a moverse.",
    seriesDefault: 3,
  },
  {
    id: "pilates-028",
    discipline: "pilates",
    name: "Criss Cross alternado",
    position: "Supino",
    modality: ["mat"],
    level: ["intermedio", "avanzado"],
    moment: 4,
    objective: ["coordinacion-fluidez", "centro"],
    avoid: ["Hernia de disco lumbar"],
    description: "Con las manos detrás de la cabeza y una rodilla al pecho, rotá el torso llevando el codo contrario hacia la rodilla, alternando de lado en un ritmo continuo y controlado.",
    howTo: "Pedí que giren desde las costillas, no tironeando del cuello con las manos.",
    adaptation: "Reducir la rotación del torso y mantener la cabeza apoyada en el piso entre repeticiones.",
    seriesDefault: 2,
  },
  {
    id: "pilates-029",
    discipline: "pilates",
    name: "Brazo y pierna cruzados en Reformer",
    position: "Prono sobre el carro, manos en las correas",
    modality: ["reformer", "mixta"],
    level: ["avanzado"],
    moment: 5,
    objective: ["coordinacion-fluidez", "centro"],
    description: "Boca abajo sobre el carro, extendé un brazo hacia adelante y la pierna opuesta hacia atrás al mismo tiempo, sosteniendo el equilibrio del carro sin que se desplace de más.",
    howTo: "Pedí que el carro se mueva lo mínimo posible mientras extienden brazo y pierna.",
    adaptation: "Realizar el movimiento sin extender por completo la pierna, manteniendo apoyo parcial en la plataforma.",
    seriesDefault: 2,
  },
  {
    id: "pilates-030",
    discipline: "pilates",
    name: "Marcha lenta con cambio de apoyo",
    position: "De pie",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio"],
    moment: 2,
    objective: ["coordinacion-fluidez", "lumbopelvica", "adultos-mayores"],
    description: "De pie, elevá una rodilla despacio hasta la cadera y apoyá el pie con control antes de repetir con la otra pierna, sosteniendo la pelvis estable durante todo el cambio de apoyo.",
    howTo: "Pedí que apoyen el pie sin golpear el piso, como si pisaran sobre algodón.",
    adaptation: "Apoyar una mano en una silla o pared para sostener el equilibrio.",
    seriesDefault: 2,
  },
  {
    id: "pilates-031",
    discipline: "pilates",
    name: "Bridging con brazos extendidos",
    position: "Supino",
    modality: ["mat"],
    level: ["inicial"],
    moment: 2,
    objective: ["lumbopelvica"],
    description: "Con las rodillas flexionadas y los brazos extendidos hacia el techo, elevá la cadera vértebra por vértebra mientras los brazos se mantienen quietos, sosteniendo unos segundos antes de bajar con control.",
    howTo: "Pedí que suban la cadera como si despegaran una vértebra a la vez del piso.",
    adaptation: "Reducir la altura de la elevación de cadera si aparece tensión lumbar.",
    seriesDefault: 3,
  },
  {
    id: "pilates-032",
    discipline: "pilates",
    name: "Mermaid lateral en sedestación",
    position: "Sentada",
    modality: ["mat", "reformer", "mixta"],
    level: ["intermedio"],
    moment: 4,
    objective: ["columna"],
    description: "Sentada con las piernas plegadas a un costado, apoyá una mano en el piso y estirá el otro brazo por encima de la cabeza, alargando el costado del torso sin colapsar el hombro de apoyo.",
    howTo: "Pedí que dejen espacio entre la oreja y el hombro de apoyo; luego repitan del otro lado.",
    adaptation: "Reducir la inclinación lateral o apoyar el antebrazo en lugar de la mano.",
    seriesDefault: 2,
  },
  {
    id: "pilates-033",
    discipline: "pilates",
    name: "Arm Circles con carga liviana en Reformer",
    position: "Sentada de espaldas al cabezal",
    modality: ["reformer", "mixta"],
    level: ["intermedio"],
    moment: 3,
    objective: ["tren-superior"],
    description: "Sentada con carga liviana en los resortes de brazos, dibujá círculos pequeños y controlados hacia adelante manteniendo los hombros alejados de las orejas y el torso erguido durante todo el movimiento.",
    howTo: "Pedí que el círculo salga del hombro, sin que la muñeca se doble para compensar.",
    seriesDefault: 2,
  },
  {
    id: "pilates-034",
    discipline: "pilates",
    name: "Pelvic Clock (reloj pélvico)",
    position: "Supino",
    modality: ["mat"],
    level: ["inicial"],
    moment: 1,
    objective: ["lumbopelvica", "adultos-mayores", "principiantes-abs", "miedo-movimiento"],
    description: "Con las rodillas flexionadas, inclina la pelvis suavemente hacia adelante y atrás, y luego hacia los costados, explorando el rango de movimiento antes de volver a la posición neutra.",
    howTo: "Pedí que imaginen un reloj sobre el abdomen y muevan la pelvis apenas hacia cada número.",
    seriesDefault: 1,
  },
  {
    id: "pilates-035",
    discipline: "pilates",
    name: "Standing Leg Press en Reformer",
    position: "De pie sobre la plataforma, manos en la barra",
    modality: ["reformer", "mixta"],
    level: ["intermedio"],
    moment: 3,
    objective: ["centro", "lumbopelvica"],
    avoid: ["Post-cirugía de rodilla"],
    description: "De pie sobre la plataforma con carga media, flexioná y extendé una pierna empujando el carro mientras la pelvis se mantiene estable y el torso erguido durante todo el recorrido.",
    howTo: "Pedí que la cadera no rote hacia el lado que empuja el carro.",
    adaptation: "Reducir el recorrido de la flexión de rodilla o trabajar con carga más liviana.",
    seriesDefault: 3,
  },
  {
    id: "pilates-036",
    discipline: "pilates",
    name: "Side Kick — preparación",
    position: "De costado",
    modality: ["mat"],
    level: ["intermedio"],
    moment: 4,
    objective: ["lumbopelvica"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Apoyada de costado con la cabeza sobre el brazo extendido, elevá la pierna de arriba a la altura de la cadera y llevala hacia adelante y atrás sin que la pelvis rote.",
    howTo: "Pedí que la cadera de arriba se mantenga apilada sobre la de abajo durante todo el recorrido.",
    adaptation: "Reducir la altura de la pierna o acortar el recorrido hacia adelante y atrás.",
    seriesDefault: 2,
  },
  {
    id: "pilates-037",
    discipline: "pilates",
    name: "Teaser — preparación",
    position: "Supino",
    modality: ["mat"],
    level: ["avanzado"],
    moment: 5,
    objective: ["centro", "columna"],
    avoid: ["Hernia de disco lumbar"],
    description: "Con las rodillas en mesa, enrollá el torso hacia arriba mientras extendés las piernas en diagonal, buscando el equilibrio sobre los isquiones con los brazos paralelos al piso.",
    howTo: "Pedí que suban despacio, sintiendo el abdomen antes que la fuerza de las piernas.",
    adaptation: "Mantener las rodillas flexionadas y los pies apoyados en el piso durante la subida.",
    seriesDefault: 2,
  },
  {
    id: "pilates-038",
    discipline: "pilates",
    name: "Reverse Plank apoyada en el carro",
    position: "Sentada en el carro, manos detrás de la cadera",
    modality: ["reformer", "mixta"],
    level: ["avanzado"],
    moment: 5,
    objective: ["tren-superior", "centro"],
    avoid: ["Embarazo / posparto"],
    description: "Sentada con las manos apoyadas detrás y los pies en la barra, elevá la cadera formando una línea recta desde los hombros hasta los talones, sosteniendo unos segundos con el centro activo.",
    howTo: "Pedí que empujen el piso con las manos para que los hombros no se hundan.",
    adaptation: "Mantener la cadera apoyada en el carro y trabajar solo la apertura de pecho.",
    seriesDefault: 2,
  },
  {
    id: "pilates-039",
    discipline: "pilates",
    name: "Roll Over — preparación",
    position: "Supino",
    modality: ["mat"],
    level: ["avanzado"],
    moment: 4,
    objective: ["columna"],
    avoid: ["Hernia de disco lumbar", "Hipermovilidad"],
    description: "Con las piernas extendidas hacia el techo, llevalas por encima de la cabeza con control hasta que la cadera se despega apenas del piso, sosteniendo el movimiento con el centro, no con el impulso.",
    howTo: "Pedí que bajen las piernas más despacio de lo que subieron.",
    adaptation: "Reducir el recorrido llevando las piernas solo hasta la vertical, sin despegar la cadera.",
    seriesDefault: 2,
  },
  {
    id: "pilates-040",
    discipline: "pilates",
    name: "Footwork variado — puntas y talones",
    position: "Supino en el carro",
    modality: ["reformer", "mixta"],
    level: ["inicial"],
    moment: 2,
    objective: ["lumbopelvica", "principiantes-abs"],
    description: "Con los pies en la barra en distintas posiciones (talones, puntas, en V), empujá y regresá el carro con carga liviana, sosteniendo la pelvis neutra en cada variante de apoyo.",
    howTo: "Pedí que noten si algún apoyo les cuesta más mantener la pelvis quieta.",
    seriesDefault: 3,
  },
  {
    id: "pilates-041",
    discipline: "pilates",
    name: "Mermaid completo en Reformer",
    position: "Sentada de costado al carro",
    modality: ["reformer", "mixta"],
    level: ["avanzado"],
    moment: 4,
    objective: ["columna", "tren-superior"],
    description: "Sentada de costado con una mano en la barra y carga liviana, inclina el torso lateralmente empujando el carro con el brazo, alargando la columna antes de volver al centro con control.",
    howTo: "Pedí que alarguen el costado antes de empujar el carro, sin colapsar sobre el brazo de apoyo.",
    seriesDefault: 2,
  },
  {
    id: "pilates-042",
    discipline: "pilates",
    name: "Estiramiento de columna en posición de niño",
    position: "De rodillas",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["columna", "adultos-mayores"],
    avoid: ["Post-cirugía de rodilla"],
    description: "De rodillas, sentate hacia atrás sobre los talones y estirá los brazos hacia adelante apoyando la frente en el piso, alargando la columna mientras respirás hacia la zona media de la espalda.",
    howTo: "Pedí que dirijan la respiración hacia las costillas de la espalda, no solo hacia el pecho.",
    adaptation: "Separar las rodillas o colocar una almohada entre los talones y los glúteos.",
    seriesDefault: 1,
  },
  {
    id: "pilates-043",
    discipline: "pilates",
    name: "Relajación final con escaneo corporal",
    position: "Supino",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["centro"],
    description: "Acostada con las piernas extendidas y los brazos relajados, recorré mentalmente cada zona del cuerpo de los pies a la cabeza, notando dónde quedó tensión y dónde se siente liviano.",
    howTo: "Guiá el recorrido en voz baja y pausada, nombrando cada zona del cuerpo.",
    seriesDefault: 1,
  },
  {
    id: "pilates-044",
    discipline: "pilates",
    name: "Puente con pelota entre las rodillas",
    position: "Supino",
    modality: ["mat"],
    level: ["inicial", "intermedio"],
    moment: 2,
    objective: ["lumbopelvica", "principiantes-abs"],
    avoid: ["Disfunción de suelo pélvico"],
    description: "Con una pelota pequeña entre las rodillas y los pies apoyados, elevá la cadera mientras sostenés una presión suave y constante sobre la pelota, coordinando la respiración con el movimiento.",
    howTo: "Pedí una presión suave y sostenida sobre la pelota, no un apriete máximo.",
    adaptation: "Realizar solo la activación con la pelota, sin elevar la cadera, si hay antecedentes de tensión pélvica.",
    seriesDefault: 2,
  },
  {
    id: "pilates-045",
    discipline: "pilates",
    name: "Transferencia de peso sentada en silla",
    position: "Sentada en el borde de una silla",
    modality: ["mat", "mixta"],
    level: ["inicial"],
    moment: 2,
    objective: ["adultos-mayores", "lumbopelvica"],
    description: "Sentada al borde de la silla con los pies apoyados, trasladá el peso del cuerpo hacia un glúteo y luego hacia el otro de forma lenta, sosteniendo la columna erguida durante todo el traslado.",
    howTo: "Pedí que sientan cómo cambia el apoyo bajo cada isquion sin inclinar el torso hacia adelante.",
    adaptation: "Reducir la amplitud del traslado de peso si aparece inestabilidad.",
    seriesDefault: 2,
  },
  {
    id: "pilates-046",
    discipline: "pilates",
    name: "Activación básica del centro en supino",
    position: "Supino",
    modality: ["mat"],
    level: ["inicial"],
    moment: 1,
    objective: ["principiantes-abs", "centro"],
    description: "Con las rodillas flexionadas y las manos apoyadas sobre el abdomen bajo, exhalá llevando el ombligo suavemente hacia la columna sin mover la pelvis ni contener la respiración, y soltá al inhalar.",
    howTo: "Pedí que sientan la activación bajo las manos solo con la exhalación, sin apretar glúteos ni abdomen alto.",
    seriesDefault: 3,
  },
  {
    id: "pilates-047",
    discipline: "pilates",
    name: "Balanceo suave de brazos sentada",
    position: "Sentada",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial"],
    moment: 1,
    objective: ["miedo-movimiento", "centro"],
    description: "Sentada con la columna erguida, balanceá los brazos hacia adelante y atrás en un recorrido pequeño y previsible, coordinando el movimiento con una respiración pareja y sin buscar velocidad.",
    howTo: "Pedí que mantengan el mismo ritmo y tamaño de movimiento en cada repetición, para generar previsibilidad.",
    seriesDefault: 3,
  },
  {
    id: "yoga-001",
    discipline: "yoga",
    name: "Respiración diafragmática (Dirga Pranayama simplificado)",
    position: "Supino",
    modality: ["suave", "dinamico", "restaurativo"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 1,
    objective: ["enraizamiento", "adultos-mayores", "principiantes-abs", "miedo-movimiento"],
    description: "Acostada con las rodillas flexionadas, apoyá una mano en el pecho y otra en el abdomen, y sentí cómo se expande primero el abdomen y luego el pecho al inhalar.",
    howTo: "Pedí que la mano del abdomen suba antes que la del pecho en cada inhalación.",
    coaching: {
      verbal: "Pedí que la mano del abdomen suba antes que la del pecho en cada inhalación.",
      imagenMental: "El abdomen se infla como un globo suave que se llena de aire antes de que el pecho se expanda.",
      tactil: "Apoyá tu mano sobre el abdomen de la alumna, con su permiso, para que sienta el movimiento antes de hacerlo sola.",
      pregunta: "¿La mano del abdomen se mueve antes o al mismo tiempo que la del pecho?",
    },
    progression: "es la base respiratoria para todos los niveles; no necesita progresión, solo sostener la atención más tiempo con la práctica",
    adaptations: {
      "Embarazo / posparto": "Elevar el torso con almohadones en lugar de estar completamente acostada, para reducir la presión sobre el abdomen.",
    },
    seriesDefault: 1,
  },
  {
    id: "yoga-002",
    discipline: "yoga",
    name: "Media torsión sentada suave (Ardha Matsyendrasana simplificada)",
    position: "Sentada",
    modality: ["suave", "dinamico"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 1,
    objective: ["columna-yoga"],
    avoid: ["Embarazo / posparto"],
    description: "Sentada con las piernas cruzadas, girá el torso hacia un lado apoyando una mano detrás y la otra sobre la rodilla opuesta, alargando la columna antes de girar.",
    howTo: "Pedí que crezcan con la inhalación y giren un poco más con la exhalación; luego repitan del otro lado.",
    adaptation: "Realizar el giro con menor amplitud o sentada sobre una manta para elevar la cadera.",
    coaching: {
      verbal: "Pedí que crezcan con la inhalación y giren un poco más con la exhalación, sin forzar.",
      imagenMental: "La columna gira como un tornillo que sube mientras se enrosca, sin perder altura.",
      tactil: "Apoyá una mano sobre el hombro más alejado para acompañar el giro sin empujar de más.",
      pregunta: "¿Sentís que el giro nace de la cintura hacia arriba, o solo mueven los hombros?",
    },
    progression: "con menor amplitud es la entrada para cualquier nivel; progresá aumentando el rango de rotación a medida que la columna se sienta más libre",
    adaptations: {
      "Embarazo / posparto": "Realizar una torsión abierta (girando hacia el lado de la pierna cruzada) en lugar de una torsión cerrada, para no comprimir el abdomen.",
      "Hernia de disco lumbar": "Reducir considerablemente la amplitud del giro y priorizar el alargamiento de columna por sobre la rotación.",
    },
    seriesDefault: 1,
  },
  {
    id: "yoga-003",
    discipline: "yoga",
    name: "Mariposa reclinada suave (Supta Baddha Konasana preparación)",
    position: "Supino",
    modality: ["suave", "restaurativo"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 1,
    objective: ["cadera", "adultos-mayores", "principiantes-abs", "miedo-movimiento"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Acostada con las plantas de los pies juntas y las rodillas cayendo hacia los costados, dejá que la gravedad abra suavemente la cadera mientras la espalda descansa apoyada.",
    howTo: "Pedí que coloquen un bloque o almohadón debajo de cada rodilla si sienten tensión.",
    seriesDefault: 1,
  },
  {
    id: "yoga-004",
    discipline: "yoga",
    name: "Plancha alta con apoyo de rodillas",
    position: "Cuadrupedia",
    modality: ["dinamico"],
    level: ["inicial", "intermedio"],
    moment: 2,
    objective: ["fuerza-yoga"],
    avoid: ["Embarazo / posparto"],
    description: "Con las manos debajo de los hombros y las rodillas apoyadas en el piso, sostené el torso en línea recta desde la cabeza hasta las rodillas, activando el abdomen.",
    howTo: "Pedí que empujen el piso alejándolo, para que los omóplatos no se hundan.",
    adaptation: "Apoyar el torso sobre los antebrazos en lugar de las manos si las muñecas molestan.",
    coaching: {
      verbal: "Pedí que empujen el piso alejándolo para que los omóplatos no se hundan entre sí.",
      imagenMental: "El torso se mantiene como una tabla apoyada sobre dos patas firmes, sin que el centro se hunda.",
      tactil: "Apoyá dos dedos entre los omóplatos para que sienta si se hunden durante la sostenida.",
      pregunta: "¿Sentís que el abdomen sostiene la postura, o el peso cae hacia la zona lumbar?",
    },
    progression: "con las rodillas apoyadas es la entrada; progresá elevando las rodillas del piso una vez que el torso se mantiene estable",
    adaptations: {
      "Embarazo / posparto": "Realizar la plancha de pie, apoyando las manos en la pared a la altura del pecho, en lugar de en el piso.",
      "Disfunción de suelo pélvico": "Acortar el tiempo de sostén y coordinar con una exhalación activa, sin retener el aire.",
    },
    seriesDefault: 2,
  },
  {
    id: "yoga-005",
    discipline: "yoga",
    name: "Postura de la silla (Utkatasana)",
    position: "De pie",
    modality: ["suave", "dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 2,
    objective: ["enraizamiento", "fuerza-yoga"],
    avoid: ["Post-cirugía de rodilla"],
    description: "De pie con los pies al ancho de cadera, flexioná las rodillas como si te sentaras en una silla, llevando los brazos hacia arriba y el peso hacia los talones.",
    howTo: "Pedí que puedan ver la punta de los pies por delante de las rodillas.",
    adaptation: "Reducir la profundidad de la flexión de rodillas o apoyar la espalda contra una pared.",
    coaching: {
      verbal: "Pedí que puedan ver la punta de los pies por delante de las rodillas mientras flexionan.",
      imagenMental: "El cuerpo se sienta sobre una silla invisible, con el peso repartido hacia los talones.",
      tactil: "Apoyá una mano sobre la zona lumbar para chequear que no se arquee en exceso al flexionar las rodillas.",
      pregunta: "¿El peso está más sobre los talones o se está yendo hacia la punta de los pies?",
    },
    progression: "con menor profundidad de flexión es más accesible; progresá bajando más la cadera a medida que el sostén sea estable",
    adaptations: {
      "Post-cirugía de rodilla": "Reducir la profundidad de la flexión de rodillas y apoyar la espalda contra una pared para descargar peso.",
      "Osteoporosis / osteopenia": "Mantener la espalda bien apoyada contra la pared durante toda la postura, evitando cualquier redondeo de columna.",
    },
    seriesDefault: 1,
  },
  {
    id: "yoga-006",
    discipline: "yoga",
    name: "Perro boca abajo (Adho Mukha Svanasana)",
    position: "Cuadrupedia",
    modality: ["dinamico"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 2,
    objective: ["columna-yoga", "fuerza-yoga", "principiantes-abs"],
    description: "Desde cuadrupedia, elevá las caderas hacia atrás y arriba formando una V invertida, alargando la columna y buscando los talones hacia el piso sin forzar la extensión de rodillas.",
    howTo: "Pedí que mantengan una leve flexión de rodillas si la espalda se redondea.",
    seriesDefault: 1,
  },
  {
    id: "yoga-007",
    discipline: "yoga",
    name: "Plancha lateral con apoyo de rodilla (Vasisthasana modificada)",
    position: "De costado",
    modality: ["dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 3,
    objective: ["fuerza-yoga"],
    description: "Apoyada sobre un antebrazo o mano y la rodilla inferior en el piso, elevá la cadera formando una línea diagonal, sosteniendo el centro activo unos segundos de cada lado.",
    howTo: "Pedí que la cadera no caiga hacia el piso durante toda la sostenida.",
    coaching: {
      verbal: "Pedí que la cadera no caiga hacia el piso durante toda la sostenida, de cada lado.",
      imagenMental: "El cuerpo forma una línea diagonal firme, como una rampa que no se dobla en el medio.",
      tactil: "Apoyá una mano debajo de la cadera para marcar la altura que tiene que sostener sin caer.",
      pregunta: "¿Sentís que la cadera se mantiene arriba todo el tiempo o va cayendo de a poco?",
    },
    progression: "con la rodilla inferior apoyada es la entrada; progresá extendiendo también la pierna inferior cuando el hombro y el centro estén firmes",
    adaptations: {
      "Problemas de cadera / prótesis": "Reducir el tiempo de sostén y trabajar con la cadera más baja, sin buscar la alineación completa.",
      "Hipermovilidad": "Evitar bloquear el codo o la muñeca de apoyo; mantener una leve flexión activa en la articulación de apoyo.",
    },
    seriesDefault: 2,
  },
  {
    id: "yoga-008",
    discipline: "yoga",
    name: "Guerrero I (Virabhadrasana I)",
    position: "De pie",
    modality: ["dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 3,
    objective: ["enraizamiento", "fuerza-yoga"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Con un pie adelante flexionado y el de atrás firme en diagonal, llevá los brazos hacia arriba y las caderas mirando al frente, sosteniendo la postura con respiración pareja.",
    howTo: "Pedí que la rodilla delantera no pase la línea del tobillo.",
    adaptation: "Acortar el paso entre los pies o apoyar las manos en la cadera en lugar de elevarlas.",
    seriesDefault: 1,
  },
  {
    id: "yoga-009",
    discipline: "yoga",
    name: "Triángulo (Trikonasana)",
    position: "De pie",
    modality: ["suave", "dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 3,
    objective: ["cadera", "columna-yoga"],
    description: "Con las piernas separadas y un pie girado hacia afuera, inclinate lateralmente desde la cadera apoyando la mano en la pierna o un bloque, y extendé el otro brazo hacia arriba.",
    howTo: "Pedí que el pecho gire hacia el techo en lugar de caer hacia el piso; luego repitan del otro lado.",
    adaptation: "Apoyar la mano en un bloque o en la espinilla en lugar de buscar el piso.",
    coaching: {
      verbal: "Pedí que el pecho gire hacia el techo en lugar de caer hacia el piso, de cada lado.",
      imagenMental: "El cuerpo se extiende entre dos paredes imaginarias, adelante y atrás, sin acortarse hacia el costado.",
      tactil: "Apoyá una mano sobre el hombro de arriba para invitar a que gire hacia el techo.",
      pregunta: "¿Sentís más estiramiento en la parte de atrás de la pierna, o el esfuerzo se va hacia la zona lumbar?",
    },
    progression: "apoyando la mano en un bloque es la entrada; progresá bajando la mano hacia la espinilla o el piso cuando el rango lo permita",
    adaptations: {
      "Hipermovilidad": "Evitar bloquear la rodilla de la pierna delantera; mantenerla con una leve flexión activa.",
      "Problemas de cadera / prótesis": "Reducir la apertura entre los pies y trabajar con menor profundidad de inclinación lateral.",
    },
    seriesDefault: 1,
  },
  {
    id: "yoga-010",
    discipline: "yoga",
    name: "Postura de la cobra (Bhujangasana)",
    position: "Prono",
    modality: ["dinamico"],
    level: ["inicial", "intermedio"],
    moment: 3,
    objective: ["columna-yoga"],
    avoid: ["Embarazo / posparto"],
    description: "Boca abajo con las manos debajo de los hombros, elevá el pecho del piso usando principalmente los músculos de la espalda, manteniendo los codos apenas flexionados y cerca del cuerpo.",
    howTo: "Pedí que alarguen la nuca en vez de echar la cabeza hacia atrás.",
    adaptation: "Elevar solo unos centímetros el pecho, apoyando los antebrazos en el piso (esfinge).",
    seriesDefault: 2,
  },
  {
    id: "yoga-011",
    discipline: "yoga",
    name: "Media luna (Ardha Chandrasana)",
    position: "De pie",
    modality: ["dinamico"],
    level: ["avanzado"],
    moment: 4,
    objective: ["fuerza-yoga", "enraizamiento"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Desde triángulo, apoyá una mano en el piso o un bloque y elevá la pierna de atrás mientras el torso rota hacia arriba, sosteniendo el equilibrio con la mirada al frente.",
    howTo: "Pedí que empujen el talón de la pierna elevada hacia atrás, como contra una pared.",
    adaptation: "Practicar cerca de una pared para apoyar la pierna elevada o mantener una mano en la cadera.",
    coaching: {
      verbal: "Pedí que empujen el talón de la pierna elevada hacia atrás, como si empujaran una pared.",
      imagenMental: "El cuerpo se abre como una estrella de mar horizontal, sostenida por un solo punto de apoyo.",
      tactil: "Apoyá una mano bajo la cadera elevada para ayudar a mantenerla nivelada con la de abajo.",
      pregunta: "¿Sentís que la cadera de arriba se abre hacia el techo, o rota hacia adelante?",
    },
    progression: "practicando cerca de una pared es la entrada a esta postura; progresá alejándote de la pared a medida que el equilibrio sea más estable",
    adaptations: {
      "Problemas de cadera / prótesis": "Practicar la variante con la mano de apoyo sobre una silla y sin elevar demasiado la pierna de atrás.",
      "Post-cirugía de rodilla": "Mantener una leve flexión en la rodilla de apoyo en lugar de buscar la extensión completa.",
    },
    seriesDefault: 1,
  },
  {
    id: "yoga-012",
    discipline: "yoga",
    name: "Media paloma reclinada con soporte",
    position: "Supino",
    modality: ["suave", "restaurativo"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 4,
    objective: ["cadera"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Acostada, cruzá un tobillo sobre la rodilla opuesta formando un cuatro, y sostené la pierna de abajo con las manos, acercando suavemente las piernas hacia el pecho.",
    howTo: "Pedí que la cabeza y los hombros se mantengan apoyados y relajados; luego repitan del otro lado.",
    adaptation: "Mantener el pie apoyado en el piso en lugar de acercar las piernas al pecho.",
    coaching: {
      verbal: "Pedí que la cabeza y los hombros se mantengan apoyados y relajados, de cada lado.",
      imagenMental: "La pierna de arriba dibuja un cuatro relajado que descansa sobre la de abajo, sin tironear.",
      tactil: "Apoyá una mano sobre el hombro para recordar que se mantenga apoyado mientras las piernas trabajan.",
      pregunta: "¿Sentís el estiramiento en el glúteo de la pierna cruzada, o se te escapa hacia la rodilla?",
    },
    progression: "manteniendo el pie apoyado en el piso es la entrada; progresá acercando las piernas hacia el pecho cuando la cadera lo permita sin dolor",
    adaptations: {
      "Problemas de cadera / prótesis": "Mantener el pie apoyado en el piso sin acercar las piernas al pecho, trabajando solo con el cruce suave del tobillo.",
      "Post-cirugía de rodilla": "Evitar la flexión profunda de la rodilla cruzada; trabajar con un ángulo más abierto entre la pierna y el torso.",
    },
    seriesDefault: 1,
  },
  {
    id: "yoga-013",
    discipline: "yoga",
    name: "Águila (Garudasana)",
    position: "De pie",
    modality: ["dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 4,
    objective: ["enraizamiento", "cadera"],
    avoid: ["Problemas de cadera / prótesis", "Post-cirugía de rodilla"],
    description: "De pie en un solo apoyo, cruzá un muslo sobre el otro enganchando el pie si es posible, y envolvé los brazos entre sí, buscando un punto fijo para sostener el equilibrio.",
    howTo: "Pedí que fijen la mirada en un punto quieto antes de cruzar los brazos.",
    adaptation: "Apoyar apenas la punta del pie en el piso en lugar de enganchar la pierna.",
    seriesDefault: 1,
  },
  {
    id: "yoga-014",
    discipline: "yoga",
    name: "Camello con apoyo (Ustrasana modificada)",
    position: "De rodillas",
    modality: ["dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 4,
    objective: ["columna-yoga"],
    avoid: ["Hipermovilidad", "Hernia de disco lumbar"],
    description: "De rodillas con las manos en la zona lumbar, empujá las caderas hacia adelante y abrí el pecho hacia arriba, extendiendo la columna sin dejar caer la cabeza de golpe.",
    howTo: "Pedí que empiecen el movimiento empujando las caderas antes de abrir el pecho.",
    adaptation: "Mantener las manos en la zona lumbar durante toda la postura, sin llevarlas a los talones.",
    seriesDefault: 1,
  },
  {
    id: "yoga-015",
    discipline: "yoga",
    name: "Flujo Guerrero II a triángulo",
    position: "De pie",
    modality: ["dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 5,
    objective: ["fuerza-yoga", "enraizamiento"],
    description: "Desde Guerrero II, extendé la pierna delantera y llevá el torso hacia adelante hasta triángulo, y volvé a flexionar para regresar, uniendo ambas posturas con la respiración.",
    howTo: "Pedí que el movimiento de ida y vuelta siga el ritmo de inhalar y exhalar; alternen el lado en la siguiente ronda.",
    coaching: {
      verbal: "Pedí que el movimiento de ida y vuelta siga el ritmo de inhalar y exhalar.",
      imagenMental: "El cuerpo fluye entre dos formas como una ola que va y viene sin cortes.",
      tactil: "No suele requerir contacto físico; guiá el ritmo con la voz marcando cada inhalación y exhalación.",
      pregunta: "¿Sentís que el cambio entre posturas es fluido, o hay una pausa brusca en el medio?",
    },
    progression: "alternando ambos lados en cada ronda es la base; progresá sosteniendo cada postura un poco más antes de fluir a la siguiente",
    adaptations: {
      "Problemas de cadera / prótesis": "Reducir la profundidad de la flexión de la rodilla delantera en Guerrero II antes de fluir hacia el triángulo.",
    },
    seriesDefault: 2,
  },
  {
    id: "yoga-016",
    discipline: "yoga",
    name: "Secuencia fluida gato-vaca a perro boca abajo",
    position: "Cuadrupedia",
    modality: ["suave", "dinamico"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 5,
    objective: ["columna-yoga"],
    description: "Encadená gato y vaca con la respiración, y en la siguiente exhalación llevá las caderas hacia atrás y arriba hasta perro boca abajo, repitiendo la secuencia varias veces.",
    howTo: "Pedí que cada cambio de postura coincida con una inhalación o una exhalación completa.",
    coaching: {
      verbal: "Pedí que cada cambio de postura coincida con una inhalación o una exhalación completa.",
      imagenMental: "La columna ondula como una serpiente que se despierta antes de estirarse por completo.",
      tactil: "Apoyá una mano sobre la zona lumbar durante gato-vaca para que sienta el recorrido completo de la columna.",
      pregunta: "¿Sentís que el movimiento nace de la pelvis y sube, o empieza directamente en los hombros?",
    },
    progression: "es una secuencia apta para todos los niveles; progresá sosteniendo más tiempo el perro boca abajo entre repeticiones",
    adaptations: {
      "Hernia de disco lumbar": "Reducir la amplitud de la extensión en vaca y priorizar el redondeo suave en gato, sin forzar el rango.",
    },
    seriesDefault: 3,
  },
  {
    id: "yoga-017",
    discipline: "yoga",
    name: "Guerrero II a ángulo lateral extendido",
    position: "De pie",
    modality: ["dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 5,
    objective: ["cadera", "enraizamiento"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Desde Guerrero II, apoyá el antebrazo sobre el muslo delantero y extendé el otro brazo por encima de la oreja, formando una línea larga desde el pie de atrás hasta la mano.",
    howTo: "Pedí que la rodilla delantera se mantenga alineada con el segundo dedo del pie; luego repitan del otro lado.",
    adaptation: "Apoyar la mano en un bloque en lugar del antebrazo sobre el muslo.",
    seriesDefault: 1,
  },
  {
    id: "yoga-018",
    discipline: "yoga",
    name: "Zapatero reclinado (Supta Baddha Konasana)",
    position: "Supino",
    modality: ["suave", "restaurativo"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["cadera", "adultos-mayores", "principiantes-abs", "miedo-movimiento"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Acostada con las plantas de los pies unidas y las rodillas apoyadas hacia los costados sobre almohadones, quedate en quietud respirando y soltando el peso de las piernas.",
    howTo: "Pedí que ajusten la altura de los almohadones hasta sentir la cadera completamente sostenida.",
    coaching: {
      verbal: "Pedí que ajusten la altura de los almohadones hasta sentir la cadera completamente sostenida.",
      imagenMental: "Las rodillas descansan como las alas de una mariposa posada, sin ningún esfuerzo activo.",
      tactil: "No requiere contacto físico; invitá a ajustar los soportes hasta que no haya ninguna tensión activa.",
      pregunta: "¿Hay algún punto de tensión activa en la cadera, o todo el peso está sostenido por los almohadones?",
    },
    progression: "es una postura de cierre apta para todos los niveles, sin necesidad de progresión",
    adaptations: {
      "Problemas de cadera / prótesis": "Colocar soportes más altos debajo de ambas rodillas para reducir la apertura de cadera al mínimo cómodo.",
      "Embarazo / posparto": "Elevar el torso con almohadones adicionales para mayor comodidad respiratoria.",
    },
    seriesDefault: 1,
  },
  {
    id: "yoga-019",
    discipline: "yoga",
    name: "Torsión reclinada suave (Supta Matsyendrasana)",
    position: "Supino",
    modality: ["suave", "restaurativo"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["columna-yoga"],
    avoid: ["Hernia de disco lumbar", "Embarazo / posparto"],
    description: "Acostada con las rodillas flexionadas, dejalas caer juntas hacia un costado mientras los brazos se abren en cruz y la mirada busca el lado contrario, respirando con calma.",
    howTo: "Pedí que ambos hombros se mantengan apoyados en el piso; luego repitan hacia el otro costado.",
    adaptation: "Colocar una almohada debajo de las rodillas para reducir el recorrido de la torsión.",
    coaching: {
      verbal: "Pedí que ambos hombros se mantengan apoyados en el piso durante toda la torsión, hacia cada lado.",
      imagenMental: "Las rodillas caen como una hoja que se apoya suavemente hacia un costado, sin peso extra.",
      tactil: "Apoyá una mano suave sobre la rodilla superior para acompañar la caída sin empujar.",
      pregunta: "¿Los dos hombros se mantienen apoyados, o uno se levanta al caer las piernas hacia el costado?",
    },
    progression: "es una torsión suave apta para todos los niveles; progresá dejando caer las piernas un poco más lejos del cuerpo si no hay molestia",
    adaptations: {
      "Hernia de disco lumbar": "Colocar una almohada debajo de las rodillas y reducir mucho el recorrido de la caída hacia el costado.",
      "Embarazo / posparto": "Evitar la torsión cerrada; reemplazar por una torsión abierta suave o simplemente dejar las rodillas apoyadas al centro con respiración.",
    },
    seriesDefault: 1,
  },
  {
    id: "yoga-020",
    discipline: "yoga",
    name: "Piernas en la pared (Viparita Karani)",
    position: "Supino",
    modality: ["suave", "restaurativo"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["enraizamiento", "adultos-mayores"],
    avoid: ["Embarazo / posparto"],
    description: "Acostada cerca de una pared, apoyá las piernas extendidas hacia arriba contra ella y dejá los brazos relajados a los costados, permaneciendo en quietud varios minutos con los ojos cerrados.",
    howTo: "Pedí que acerquen o alejen la cadera de la pared hasta sentir las piernas cómodas.",
    adaptation: "Doblar las rodillas o alejar la cadera de la pared si sienten tirantez detrás de las piernas.",
    seriesDefault: 1,
  },
  {
    id: "yoga-021",
    discipline: "yoga",
    name: "Postura de la montaña con activación de pies (Tadasana)",
    position: "De pie",
    modality: ["suave"],
    level: ["inicial"],
    moment: 1,
    objective: ["enraizamiento", "principiantes-abs"],
    description: "De pie con los pies al ancho de cadera, repartí el peso entre los cuatro puntos de apoyo del pie y sentí cómo la postura se organiza desde el piso hacia arriba.",
    howTo: "Pedí que noten si el peso cae más hacia los talones o hacia los dedos, y busquen el centro.",
    seriesDefault: 1,
  },
  {
    id: "yoga-022",
    discipline: "yoga",
    name: "Flexión lateral de pie",
    position: "De pie",
    modality: ["suave", "dinamico"],
    level: ["intermedio"],
    moment: 2,
    objective: ["columna-yoga"],
    description: "De pie con los pies juntos, elevá un brazo y flexioná el torso hacia el lado contrario, alargando la cintura antes de inclinarte, y volvé al centro con control.",
    howTo: "Pedí que crezcan con la inhalación antes de inclinarse hacia el costado; luego repitan del otro lado.",
    adaptation: "Reducir la inclinación lateral o apoyar la mano libre en la cadera.",
    seriesDefault: 1,
  },
  {
    id: "yoga-023",
    discipline: "yoga",
    name: "Guerrero III con apoyo (Virabhadrasana III modificada)",
    position: "De pie",
    modality: ["dinamico"],
    level: ["avanzado"],
    moment: 4,
    objective: ["fuerza-yoga", "cadera"],
    description: "Desde una pierna, inclina el torso hacia adelante mientras la otra pierna se extiende hacia atrás, buscando una línea recta desde la cabeza hasta el talón, sosteniendo el equilibrio con la mirada fija.",
    howTo: "Pedí que estiren la pierna de atrás como si empujaran una pared invisible con el talón.",
    adaptation: "Mantener las manos apoyadas en un bloque o silla al frente para sostener el equilibrio.",
    seriesDefault: 1,
  },
  {
    id: "yoga-024",
    discipline: "yoga",
    name: "Postura del árbol (Vrksasana)",
    position: "De pie",
    modality: ["suave", "dinamico"],
    level: ["inicial", "intermedio"],
    moment: 2,
    objective: ["enraizamiento"],
    description: "De pie sobre una pierna, apoyá la planta del otro pie en la pantorrilla o el muslo, evitando la rodilla, y juntá las manos al frente del pecho sosteniendo la mirada en un punto fijo.",
    howTo: "Pedí que fijen la mirada antes de levantar el pie del piso.",
    adaptation: "Apoyar apenas la punta del pie en el piso junto al tobillo de la pierna de base.",
    seriesDefault: 1,
  },
  {
    id: "yoga-025",
    discipline: "yoga",
    name: "Paloma con apoyo de bloque (Eka Pada Rajakapotasana modificada)",
    position: "Sentada",
    modality: ["dinamico"],
    level: ["intermedio"],
    moment: 4,
    objective: ["cadera"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Con una pierna flexionada al frente y la otra extendida hacia atrás, apoyá un bloque debajo del glúteo de la pierna flexionada si la cadera no llega cómoda al piso, y respirá sosteniendo la postura.",
    howTo: "Pedí que ajusten la altura del bloque hasta sentir la cadera estable, sin dolor agudo.",
    adaptation: "Realizar la variante reclinada con la pierna en cuatro, en lugar de la versión sentada.",
    seriesDefault: 1,
  },
  {
    id: "yoga-026",
    discipline: "yoga",
    name: "Postura del niño (Balasana)",
    position: "De rodillas",
    modality: ["restaurativo", "suave"],
    level: ["inicial"],
    moment: 1,
    objective: ["columna-yoga", "principiantes-abs", "miedo-movimiento"],
    avoid: ["Embarazo / posparto"],
    description: "De rodillas, sentate hacia atrás sobre los talones y estirá los brazos hacia adelante o dejalos al costado del cuerpo, apoyando la frente en el piso y respirando con calma.",
    howTo: "Pedí que sientan el peso del cuerpo entregado por completo al piso en cada exhalación.",
    adaptation: "Separar las rodillas para dejar espacio al abdomen, o apoyar un almohadón bajo el torso.",
    seriesDefault: 1,
  },
  {
    id: "yoga-027",
    discipline: "yoga",
    name: "Plancha invertida sentada (Purvottanasana modificada)",
    position: "Sentada",
    modality: ["dinamico"],
    level: ["avanzado"],
    moment: 4,
    objective: ["fuerza-yoga"],
    avoid: ["Hernia de disco lumbar"],
    description: "Sentada con las manos apoyadas detrás de la cadera y los dedos apuntando hacia adelante, elevá la cadera formando una línea desde los hombros hasta los talones, sosteniendo con el centro activo.",
    howTo: "Pedí que empujen el piso con las manos para que los hombros no se hundan hacia las orejas.",
    adaptation: "Mantener la cadera apoyada en el piso y trabajar solo la apertura del pecho.",
    seriesDefault: 1,
  },
  {
    id: "yoga-028",
    discipline: "yoga",
    name: "Postura del puente (Setu Bandha Sarvangasana)",
    position: "Supino",
    modality: ["dinamico", "suave"],
    level: ["intermedio"],
    moment: 3,
    objective: ["fuerza-yoga", "columna-yoga"],
    description: "Con las rodillas flexionadas y los pies apoyados, elevá la cadera hacia el techo mientras las manos se entrelazan debajo del cuerpo, sosteniendo la postura con la respiración pareja.",
    howTo: "Pedí que empujen los pies contra el piso para elevar la cadera, en lugar de arquear solo la espalda.",
    adaptation: "Colocar un bloque debajo del sacro para sostener la postura sin esfuerzo activo.",
    seriesDefault: 1,
  },
  {
    id: "yoga-029",
    discipline: "yoga",
    name: "Media pinza sentada (Ardha Paschimottanasana)",
    position: "Sentada",
    modality: ["suave"],
    level: ["inicial", "intermedio"],
    moment: 3,
    objective: ["columna-yoga", "cadera"],
    avoid: ["Hernia de disco lumbar"],
    description: "Sentada con una pierna extendida y la otra flexionada hacia adentro, inclina el torso hacia adelante desde la cadera manteniendo la columna larga, sin buscar tocar el pie a costa de redondear la espalda.",
    howTo: "Pedí que inclinen desde la cadera, no desde los hombros; luego repitan del otro lado.",
    adaptation: "Sentarse sobre una manta doblada o flexionar más la rodilla de la pierna extendida.",
    seriesDefault: 1,
  },
  {
    id: "yoga-030",
    discipline: "yoga",
    name: "Postura de la rana suave (variante reclinada)",
    position: "Prono",
    modality: ["restaurativo"],
    level: ["intermedio"],
    moment: 4,
    objective: ["cadera"],
    avoid: ["Embarazo / posparto", "Problemas de cadera / prótesis"],
    description: "Boca abajo con los antebrazos apoyados al frente, separá las rodillas hacia los costados dejando que la gravedad abra la cadera gradualmente, sosteniendo la postura con respiración lenta y sin forzar el rango.",
    howTo: "Pedí que ajusten la apertura de rodillas hasta sentir un estiramiento cómodo, nunca dolor agudo.",
    adaptation: "Reducir la separación de rodillas o colocar almohadones debajo de los muslos.",
    seriesDefault: 1,
  },
  {
    id: "yoga-031",
    discipline: "yoga",
    name: "Gato-vaca con foco en la pelvis",
    position: "Cuadrupedia",
    modality: ["suave"],
    level: ["inicial"],
    moment: 1,
    objective: ["columna-yoga", "principiantes-abs"],
    description: "En cuadrupedia, inclina la pelvis hacia adelante arqueando suavemente la espalda al inhalar, y hacia atrás redondeando la columna al exhalar, moviendo la columna completa de forma segmentada.",
    howTo: "Pedí que el movimiento empiece siempre desde la pelvis y luego suba hacia el resto de la columna.",
    seriesDefault: 2,
  },
  {
    id: "yoga-032",
    discipline: "yoga",
    name: "Equilibrio en un pie con apoyo en pared",
    position: "De pie",
    modality: ["suave"],
    level: ["inicial"],
    moment: 2,
    objective: ["enraizamiento", "adultos-mayores"],
    description: "De pie cerca de una pared, apoyá los dedos suavemente en ella mientras elevás una rodilla a la altura de la cadera, sosteniendo el equilibrio sobre el pie de apoyo unos segundos.",
    howTo: "Pedí que usen la pared solo como referencia, sin apoyar todo el peso en ella.",
    adaptation: "Mantener el apoyo completo de la mano en la pared si el equilibrio resulta inestable.",
    seriesDefault: 1,
  },
  {
    id: "yoga-033",
    discipline: "yoga",
    name: "Secuencia de saludo al sol simplificado",
    position: "De pie",
    modality: ["dinamico"],
    level: ["intermedio"],
    moment: 5,
    objective: ["fuerza-yoga", "enraizamiento"],
    description: "Encadená de pie, flexión hacia adelante, media flexión con espalda plana y vuelta a de pie, coordinando cada cambio de postura con una inhalación o una exhalación completa.",
    howTo: "Pedí que sigan el ritmo de la respiración antes que la velocidad del movimiento.",
    adaptation: "Flexionar las rodillas en la flexión hacia adelante si los isquiotibiales están tensos.",
    seriesDefault: 3,
  },
  {
    id: "yoga-034",
    discipline: "yoga",
    name: "Postura del saltamontes suave (Salabhasana modificada)",
    position: "Prono",
    modality: ["dinamico"],
    level: ["intermedio"],
    moment: 4,
    objective: ["fuerza-yoga", "columna-yoga"],
    avoid: ["Embarazo / posparto"],
    description: "Boca abajo con los brazos extendidos al frente, elevá levemente el pecho y las piernas del piso al mismo tiempo, sosteniendo unos segundos con la mirada hacia el piso para no comprimir el cuello.",
    howTo: "Pedí que alarguen desde la coronilla hasta los talones en lugar de buscar altura.",
    adaptation: "Elevar solo el torso o solo las piernas por separado, en lugar de ambos a la vez.",
    seriesDefault: 2,
  },
  {
    id: "yoga-035",
    discipline: "yoga",
    name: "Respiración con sonido Ujjayi guiada",
    position: "Sentada",
    modality: ["restaurativo", "suave"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["enraizamiento", "adultos-mayores", "miedo-movimiento"],
    description: "Sentada con la columna erguida, respirá contrayendo levemente la parte posterior de la garganta para generar un sonido suave y constante, sosteniendo un ritmo parejo entre inhalación y exhalación.",
    howTo: "Pedí que imaginen empañar un espejo con la boca cerrada, para encontrar el sonido de la respiración.",
    seriesDefault: 1,
  },
  {
    id: "yoga-036",
    discipline: "yoga",
    name: "Savasana guiada con escaneo corporal",
    position: "Supino",
    modality: ["restaurativo"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["enraizamiento", "adultos-mayores", "principiantes-abs", "miedo-movimiento"],
    description: "Acostada con las piernas separadas y los brazos relajados a los costados, recorré mentalmente cada zona del cuerpo dejando que se afloje el peso sobre el piso, sin corregir ni intervenir.",
    howTo: "Guiá el recorrido corporal en voz baja y pausada, dejando silencios entre cada zona nombrada.",
    seriesDefault: 1,
  },
  {
    id: "yoga-037",
    discipline: "yoga",
    name: "Postura de la montaña con apoyo en silla",
    position: "De pie, sujeta al respaldo de una silla",
    modality: ["suave"],
    level: ["inicial"],
    moment: 2,
    objective: ["enraizamiento", "adultos-mayores"],
    description: "De pie detrás de una silla sosteniendo el respaldo con ambas manos, elevá los talones despacio y bajá con control, trabajando el equilibrio con un punto de apoyo firme y disponible.",
    howTo: "Pedí que apoyen las manos livianas sobre el respaldo, usándolo como referencia y no como sostén total.",
    adaptation: "Mantener ambos talones apoyados en el piso y trabajar solo el reparto de peso entre los pies.",
    seriesDefault: 2,
  },
  {
    id: "yoga-038",
    discipline: "yoga",
    name: "Respiración con conteo simple",
    position: "Sentada",
    modality: ["suave", "restaurativo"],
    level: ["inicial"],
    moment: 1,
    objective: ["enraizamiento", "principiantes-abs"],
    description: "Sentada con la columna erguida y los ojos cerrados o la mirada baja, inhalá contando hasta cuatro y exhalá contando hasta cuatro, sin pausas forzadas entre una respiración y otra.",
    howTo: "Pedí que cuenten en silencio, ajustando el número si cuatro tiempos resulta incómodo.",
    seriesDefault: 1,
  },
  {
    id: "yoga-039",
    discipline: "yoga",
    name: "Secuencia predecible de brazos en silla",
    position: "Sentada en una silla",
    modality: ["suave", "restaurativo"],
    level: ["inicial"],
    moment: 2,
    objective: ["miedo-movimiento", "principiantes-abs"],
    description: "Sentada con los pies apoyados, elevá ambos brazos al inhalar y bajalos al exhalar, repitiendo siempre la misma secuencia y el mismo ritmo para generar una referencia corporal previsible.",
    howTo: "Pedí que anticipen en voz alta si sigue una inhalación o una exhalación antes de cada movimiento.",
    adaptation: "Reducir la altura de los brazos si aparece tensión en los hombros o el cuello.",
    seriesDefault: 3,
  },
]