/* ============================================================
   BASE DE DATOS DE EJERCICIOS
   ------------------------------------------------------------
   Esto es una base de EJEMPLO para que el generador funcione
   de punta a punta. La idea es que la vayas reemplazando por
   tu contenido real (o el de la instructora que lo valide).

   Cada ejercicio tiene esta forma:

   {
     id: string único
     discipline: "pilates" | "yoga"
     name: string
     position: string (texto libre, ej "Supino", "De pie")
     modality: ["mat","reformer"] o ["suave","dinamico","restaurativo"]
     level: ["inicial","intermedio","avanzado"]
     moment: 1 a 6  -> a qué bloque de la clase pertenece
     objective: ["id-de-objetivo", ...]
     avoid: ["tag-contraindicacion", ...]  (opcional)
     description: texto que ve la alumna/instructora
     howTo: cómo explicarlo (opcional)
     adaptation: adaptación por patología (opcional, texto orientativo)
     seriesDefault: número de series sugeridas
   }
   ============================================================ */

const BLOCKS = [
  { id: 1, name: "Preparación",         subtitle: "Conectar con el cuerpo y la respiración",     weight: 0.15, optional: true },
  { id: 2, name: "Activación",          subtitle: "Despertar el centro, sentar las bases",        weight: 0.17 },
  { id: 3, name: "Desarrollo Principal",subtitle: "El patrón central, ligado al objetivo elegido",weight: 0.22 },
  { id: 4, name: "Profundización",      subtitle: "Variación, carga o coordinación sobre lo aprendido", weight: 0.17 },
  { id: 5, name: "Integración",         subtitle: "Secuencia fluida que une lo trabajado",        weight: 0.14 },
  { id: 6, name: "Cierre",              subtitle: "Vuelta al eje, respiración, sensación final",  weight: 0.15 },
];

const OBJECTIVES = {
  pilates: [
    { id: "lumbopelvica", label: "Estabilidad Lumbopélvica" },
    { id: "columna", label: "Movilidad de Columna" },
    { id: "tren-superior", label: "Fuerza de Tren Superior" },
    { id: "centro", label: "Conexión con el Centro" },
  ],
  yoga: [
    { id: "enraizamiento", label: "Equilibrio y Enraizamiento" },
    { id: "cadera", label: "Apertura de Cadera" },
    { id: "columna-yoga", label: "Flexibilidad de Columna" },
    { id: "fuerza-yoga", label: "Fuerza y Estabilidad" },
  ],
};

const MODALITIES = {
  pilates: [
    { id: "mat", label: "Mat" },
    { id: "reformer", label: "Reformer" },
    { id: "mixta", label: "Mixta" },
  ],
  yoga: [
    { id: "suave", label: "Suave" },
    { id: "dinamico", label: "Dinámico" },
    { id: "restaurativo", label: "Restaurativo" },
  ],
};

const POPULATIONS = [
  { id: "general", label: "Adultos (general)" },
  { id: "mayores", label: "Adultos mayores" },
  { id: "embarazo", label: "Embarazo / posparto" },
  { id: "principiantes", label: "Principiantes absolutas" },
];

const AVOID_TAGS = [
  "Hernia de disco lumbar",
  "Embarazo / posparto",
  "Problemas de cadera / prótesis",
  "Post-cirugía de rodilla",
  "Hipermovilidad",
  "Disfunción de suelo pélvico",
];

const EXERCISES = [
  {
    id: "pilates-001",
    discipline: "pilates",
    name: "Respiración lateral en cuadrupedia",
    position: "Cuadrupedia",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 1,
    objective: ["centro"],
    description: "Apoyada en manos y rodillas, dirigí el aire hacia las costillas laterales al inhalar y sentí cómo se estrechan al exhalar, activando el centro antes de empezar a moverte.",
    howTo: "Pedí que sientan que las costillas se abren como un acordeón hacia los costados.",
    adaptation: "Si las muñecas molestan, apoyar los antebrazos en el piso en lugar de las manos.",
    seriesDefault: 1,
  },
  {
    id: "pilates-002",
    discipline: "pilates",
    name: "Rodar hacia abajo (Roll Down)",
    position: "De pie",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 1,
    objective: ["columna"],
    avoid: ["Hipermovilidad"],
    description: "De pie, dejá caer la cabeza y desenrollá la columna vértebra por vértebra hacia el piso, soltando cuello y hombros, y luego subí enrollando desde la base.",
    howTo: "Contá las vértebras en voz baja mientras bajan, como si fueran cuentas de un collar.",
    adaptation: "Flexionar las rodillas si los isquiotibiales están tensos o si aparece molestia lumbar.",
    seriesDefault: 2,
  },
  {
    id: "pilates-003",
    discipline: "pilates",
    name: "Pies en la barra — activación de neutro",
    position: "Supino en el carro",
    modality: ["reformer", "mixta"],
    level: ["inicial", "intermedio"],
    moment: 1,
    objective: ["lumbopelvica"],
    description: "Con los pies apoyados en la barra y carga liviana, encontrá la posición neutra de la pelvis y sostenela mientras el carro se desliza apenas, sin perder el apoyo lumbar.",
    howTo: "Pedí que noten si la zona lumbar se despega del carro al moverse.",
    seriesDefault: 2,
  },
  {
    id: "pilates-004",
    discipline: "pilates",
    name: "The Hundred — preparación",
    position: "Supino",
    modality: ["mat"],
    level: ["inicial", "intermedio"],
    moment: 2,
    objective: ["centro"],
    description: "Con las rodillas en mesa y la cabeza apoyada, bombeá los brazos suavemente al costado del cuerpo mientras sostenés la respiración en cinco tiempos, activando el centro sin tensar el cuello.",
    howTo: "Si el cuello tensa, pedí que apoyen la cabeza y trabajen solo con los brazos.",
    adaptation: "Mantener la cabeza apoyada en el piso durante toda la serie si el cuello se fatiga.",
    seriesDefault: 1,
  },
  {
    id: "pilates-005",
    discipline: "pilates",
    name: "Push Through Bar — remo sentado",
    position: "Sentada en el carro",
    modality: ["reformer", "mixta"],
    level: ["intermedio", "avanzado"],
    moment: 2,
    objective: ["tren-superior"],
    description: "Sentada de espaldas al cabezal, empujá la barra hacia adelante y abajo con carga liviana, organizando primero las escápulas y luego extendiendo los codos con control.",
    howTo: "Pedí que bajen los omóplatos antes de que las manos se muevan un centímetro.",
    seriesDefault: 3,
  },
  {
    id: "pilates-006",
    discipline: "pilates",
    name: "Rotación de columna sentada (Spine Twist)",
    position: "Sentada",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 2,
    objective: ["columna"],
    avoid: ["Hernia de disco lumbar"],
    description: "Sentada con piernas extendidas y brazos abiertos, rotá el torso hacia un lado en dos pulsos breves manteniendo la pelvis fija, y volvé al centro con control.",
    howTo: "La pelvis no gira con el torso: si se mueve, achicá el recorrido de la rotación.",
    adaptation: "Reducir el rango de rotación o realizarla con las rodillas flexionadas y apoyadas.",
    seriesDefault: 3,
  },
  {
    id: "pilates-007",
    discipline: "pilates",
    name: "Single Leg Stretch — preparación",
    position: "Supino",
    modality: ["mat"],
    level: ["inicial", "intermedio"],
    moment: 3,
    objective: ["lumbopelvica", "centro"],
    description: "Con una rodilla al pecho y la otra pierna extendida en el aire, sostené el torso estable mientras alternás las piernas de forma lenta y controlada.",
    howTo: "Pedí que mantengan la zona lumbar apoyada, sin que se despegue al cambiar de pierna.",
    adaptation: "Apoyar la cabeza en el piso y mantener ambas rodillas flexionadas si el cuello o el abdomen se fatigan.",
    seriesDefault: 3,
  },
  {
    id: "pilates-008",
    discipline: "pilates",
    name: "Elephant (perro que camina en el carro)",
    position: "De pie en el carro, manos en la barra",
    modality: ["reformer", "mixta"],
    level: ["intermedio", "avanzado"],
    moment: 3,
    objective: ["centro", "lumbopelvica"],
    description: "Con las manos en la barra y los talones apoyados en la plataforma, empujá el carro alejando la cadera hacia atrás mientras mantenés la columna larga y el centro conectado.",
    howTo: "Pedí que alejen más la cadera de las manos que las manos de los pies.",
    adaptation: "Trabajar con las rodillas ligeramente flexionadas si los isquiotibiales están muy tensos.",
    seriesDefault: 3,
  },
  {
    id: "pilates-009",
    discipline: "pilates",
    name: "The Hundred (completo)",
    position: "Supino",
    modality: ["mat"],
    level: ["intermedio", "avanzado"],
    moment: 3,
    objective: ["centro", "columna"],
    avoid: ["Hernia de disco lumbar"],
    description: "Con el torso enrollado y las piernas extendidas en diagonal, bombeá los brazos con energía sosteniendo el abdomen conectado y el cuello relajado durante toda la serie de respiraciones.",
    howTo: "Si el cuello se tensa, pedí que bajen la cabeza y sigan solo con las piernas.",
    adaptation: "Mantener las rodillas flexionadas en mesa y la cabeza apoyada para reducir la exigencia abdominal y cervical.",
    seriesDefault: 1,
  },
  {
    id: "pilates-010",
    discipline: "pilates",
    name: "Chest Expansion (expansión de pecho)",
    position: "De rodillas en el carro",
    modality: ["reformer", "mixta"],
    level: ["intermedio", "avanzado"],
    moment: 3,
    objective: ["tren-superior", "columna"],
    description: "Arrodillada de espaldas al cabezal, tirá de las correas hacia atrás mientras la columna se mantiene larga, y girá la cabeza hacia cada lado antes de volver al centro.",
    howTo: "Pedí que el movimiento salga de los hombros hacia atrás, no de arquear la espalda.",
    seriesDefault: 3,
  },
  {
    id: "pilates-011",
    discipline: "pilates",
    name: "Single Leg Circles",
    position: "Supino",
    modality: ["mat"],
    level: ["intermedio"],
    moment: 4,
    objective: ["lumbopelvica"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Con una pierna extendida hacia el techo, dibujá círculos amplios y controlados mientras la pelvis permanece completamente quieta; luego repetí la misma cantidad con la otra pierna.",
    howTo: "Si la pelvis se balancea, pedí que achiquen el círculo hasta recuperar el control.",
    adaptation: "Flexionar levemente la rodilla de la pierna que se mueve para reducir la palanca.",
    seriesDefault: 3,
  },
  {
    id: "pilates-012",
    discipline: "pilates",
    name: "Triceps Press (elbows into springs)",
    position: "Sentada de espaldas al cabezal",
    modality: ["reformer", "mixta"],
    level: ["intermedio", "avanzado"],
    moment: 4,
    objective: ["tren-superior"],
    description: "Con los codos apoyados en el cabezal y carga liviana, extendé los antebrazos hacia atrás sin mover los hombros, sosteniendo el torso erguido y el centro activo.",
    howTo: "Pedí que los codos queden fijos como bisagras: solo se mueve el antebrazo.",
    seriesDefault: 3,
  },
  {
    id: "pilates-013",
    discipline: "pilates",
    name: "Saw (Sierra)",
    position: "Sentada, piernas abiertas",
    modality: ["mat"],
    level: ["intermedio", "avanzado"],
    moment: 4,
    objective: ["columna", "centro"],
    avoid: ["Hernia de disco lumbar"],
    description: "Sentada con las piernas abiertas, rotá el torso hacia un lado y estirá el brazo opuesto hacia el pie como serruchando, manteniendo ambos isquiones apoyados en el piso.",
    howTo: "Pedí que ambos isquiones se mantengan apoyados durante toda la rotación hacia los dos lados.",
    adaptation: "Reducir la flexión hacia adelante y mantener la columna más erguida durante la rotación.",
    seriesDefault: 3,
  },
  {
    id: "pilates-014",
    discipline: "pilates",
    name: "Knee Stretch redondo",
    position: "Cuadrupedia sobre el carro",
    modality: ["reformer", "mixta"],
    level: ["intermedio", "avanzado"],
    moment: 4,
    objective: ["centro"],
    avoid: ["Post-cirugía de rodilla"],
    description: "Con las rodillas sobre la plataforma y las manos en la barra, redondeá la columna y alejá el carro empujando desde el centro, sin perder la curva de la espalda.",
    howTo: "Pedí que imaginen que abrazan una pelota grande con el abdomen durante todo el movimiento.",
    seriesDefault: 3,
  },
  {
    id: "pilates-015",
    discipline: "pilates",
    name: "Swimming (Natación)",
    position: "Prono",
    modality: ["mat"],
    level: ["intermedio", "avanzado"],
    moment: 5,
    objective: ["centro", "columna"],
    avoid: ["Embarazo / posparto"],
    description: "Boca abajo con brazos y piernas extendidos, elevá levemente brazo y pierna opuestos alternando en un ritmo continuo, como si nadaras, sosteniendo el centro activo todo el tiempo.",
    howTo: "Pedí un movimiento chico y rápido, sin que la zona lumbar se comprima.",
    adaptation: "Reducir la altura de brazos y piernas o trabajar de a un lado por vez.",
    seriesDefault: 2,
  },
  {
    id: "pilates-016",
    discipline: "pilates",
    name: "Long Stretch (plancha en el carro)",
    position: "De pie, manos en la barra, carro móvil",
    modality: ["reformer", "mixta"],
    level: ["avanzado"],
    moment: 5,
    objective: ["centro", "tren-superior"],
    avoid: ["Embarazo / posparto", "Disfunción de suelo pélvico"],
    description: "En posición de plancha con las manos en la barra, empujá el carro alejándolo con las piernas mientras el cuerpo se mantiene en una línea recta de cabeza a talones.",
    howTo: "Pedí que la cadera no suba ni baje: la línea del cuerpo se mantiene entera.",
    adaptation: "Realizar el movimiento con las rodillas apoyadas en la plataforma en lugar de en plancha completa.",
    seriesDefault: 3,
  },
  {
    id: "pilates-017",
    discipline: "pilates",
    name: "Push-up modificado sobre rodillas",
    position: "Cuadrupedia",
    modality: ["mat", "reformer", "mixta"],
    level: ["intermedio", "avanzado"],
    moment: 5,
    objective: ["tren-superior", "centro"],
    description: "Con las rodillas apoyadas y las manos debajo de los hombros, flexioná los codos hacia atrás bajando el pecho con control, manteniendo la columna larga durante todo el recorrido.",
    howTo: "Pedí que los codos se deslicen hacia atrás, cerca de las costillas, no hacia afuera.",
    seriesDefault: 3,
  },
  {
    id: "pilates-018",
    discipline: "pilates",
    name: "Postura de descanso (Rest Position)",
    position: "De rodillas",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["columna"],
    avoid: ["Post-cirugía de rodilla"],
    description: "Sentate hacia atrás sobre los talones con los brazos extendidos al frente, soltando el peso de la espalda y respirando hacia la zona lumbar durante unas respiraciones.",
    howTo: "Pedí que sientan cómo se separan las vértebras con cada exhalación.",
    adaptation: "Colocar una almohada entre los talones y los glúteos si hay molestia en rodillas o tobillos.",
    seriesDefault: 1,
  },
  {
    id: "pilates-019",
    discipline: "pilates",
    name: "Respiración final en neutro",
    position: "Supino",
    modality: ["mat", "reformer", "mixta"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["centro", "lumbopelvica"],
    description: "Acostada con las rodillas flexionadas, volvé a la columna neutra del comienzo y notá los cambios en el apoyo, la respiración y la tensión general del cuerpo.",
    howTo: "Invitá a comparar en silencio cómo se siente el cuerpo ahora respecto al inicio de la clase.",
    seriesDefault: 1,
  },
  {
    id: "pilates-020",
    discipline: "pilates",
    name: "Estiramiento cruzado de cadera en supino",
    position: "Supino",
    modality: ["mat"],
    level: ["inicial", "intermedio"],
    moment: 6,
    objective: ["lumbopelvica"],
    avoid: ["Hernia de disco lumbar"],
    description: "Con las rodillas flexionadas, dejá caer ambas piernas juntas hacia un costado sosteniendo los hombros apoyados en el piso, estirando suavemente la zona lumbar y la cadera.",
    howTo: "Pedí que los hombros no se despeguen del piso; luego repetí llevando las piernas hacia el otro costado.",
    adaptation: "Reducir el recorrido del descenso de las piernas o colocar una almohada de apoyo entre las rodillas.",
    seriesDefault: 1,
  },

  {
    id: "yoga-001",
    discipline: "yoga",
    name: "Respiración diafragmática (Dirga Pranayama simplificado)",
    position: "Supino",
    modality: ["suave", "dinamico", "restaurativo"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 1,
    objective: ["enraizamiento"],
    description: "Acostada con las rodillas flexionadas, apoyá una mano en el pecho y otra en el abdomen, y sentí cómo se expande primero el abdomen y luego el pecho al inhalar.",
    howTo: "Pedí que la mano del abdomen suba antes que la del pecho en cada inhalación.",
    seriesDefault: 1,
  },
  {
    id: "yoga-002",
    discipline: "yoga",
    name: "Media torsión sentada suave (Ardha Matsyendrasana simplificada)",
    position: "Sentada",
    modality: ["suave", "dinamico"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 1,
    objective: ["columna-yoga"],
    avoid: ["Embarazo / posparto"],
    description: "Sentada con las piernas cruzadas, girá el torso hacia un lado apoyando una mano detrás y la otra sobre la rodilla opuesta, alargando la columna antes de girar.",
    howTo: "Pedí que crezcan con la inhalación y giren un poco más con la exhalación; luego repitan del otro lado.",
    adaptation: "Realizar el giro con menor amplitud o sentada sobre una manta para elevar la cadera.",
    seriesDefault: 1,
  },
  {
    id: "yoga-003",
    discipline: "yoga",
    name: "Mariposa reclinada suave (Supta Baddha Konasana preparación)",
    position: "Supino",
    modality: ["suave", "restaurativo"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 1,
    objective: ["cadera"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Acostada con las plantas de los pies juntas y las rodillas cayendo hacia los costados, dejá que la gravedad abra suavemente la cadera mientras la espalda descansa apoyada.",
    howTo: "Pedí que coloquen un bloque o almohadón debajo de cada rodilla si sienten tensión.",
    seriesDefault: 1,
  },
  {
    id: "yoga-004",
    discipline: "yoga",
    name: "Plancha alta con apoyo de rodillas",
    position: "Cuadrupedia",
    modality: ["dinamico"],
    level: ["inicial", "intermedio"],
    moment: 2,
    objective: ["fuerza-yoga"],
    avoid: ["Embarazo / posparto"],
    description: "Con las manos debajo de los hombros y las rodillas apoyadas en el piso, sostené el torso en línea recta desde la cabeza hasta las rodillas, activando el abdomen.",
    howTo: "Pedí que empujen el piso alejándolo, para que los omóplatos no se hundan.",
    adaptation: "Apoyar el torso sobre los antebrazos en lugar de las manos si las muñecas molestan.",
    seriesDefault: 2,
  },
  {
    id: "yoga-005",
    discipline: "yoga",
    name: "Postura de la silla (Utkatasana)",
    position: "De pie",
    modality: ["suave", "dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 2,
    objective: ["enraizamiento", "fuerza-yoga"],
    avoid: ["Post-cirugía de rodilla"],
    description: "De pie con los pies al ancho de cadera, flexioná las rodillas como si te sentaras en una silla, llevando los brazos hacia arriba y el peso hacia los talones.",
    howTo: "Pedí que puedan ver la punta de los pies por delante de las rodillas.",
    adaptation: "Reducir la profundidad de la flexión de rodillas o apoyar la espalda contra una pared.",
    seriesDefault: 1,
  },
  {
    id: "yoga-006",
    discipline: "yoga",
    name: "Perro boca abajo (Adho Mukha Svanasana)",
    position: "Cuadrupedia",
    modality: ["dinamico"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 2,
    objective: ["columna-yoga", "fuerza-yoga"],
    description: "Desde cuadrupedia, elevá las caderas hacia atrás y arriba formando una V invertida, alargando la columna y buscando los talones hacia el piso sin forzar la extensión de rodillas.",
    howTo: "Pedí que mantengan una leve flexión de rodillas si la espalda se redondea.",
    seriesDefault: 1,
  },
  {
    id: "yoga-007",
    discipline: "yoga",
    name: "Plancha lateral con apoyo de rodilla (Vasisthasana modificada)",
    position: "De costado",
    modality: ["dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 3,
    objective: ["fuerza-yoga"],
    description: "Apoyada sobre un antebrazo o mano y la rodilla inferior en el piso, elevá la cadera formando una línea diagonal, sosteniendo el centro activo unos segundos de cada lado.",
    howTo: "Pedí que la cadera no caiga hacia el piso durante toda la sostenida.",
    seriesDefault: 2,
  },
  {
    id: "yoga-008",
    discipline: "yoga",
    name: "Guerrero I (Virabhadrasana I)",
    position: "De pie",
    modality: ["dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 3,
    objective: ["enraizamiento", "fuerza-yoga"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Con un pie adelante flexionado y el de atrás firme en diagonal, llevá los brazos hacia arriba y las caderas mirando al frente, sosteniendo la postura con respiración pareja.",
    howTo: "Pedí que la rodilla delantera no pase la línea del tobillo.",
    adaptation: "Acortar el paso entre los pies o apoyar las manos en la cadera en lugar de elevarlas.",
    seriesDefault: 1,
  },
  {
    id: "yoga-009",
    discipline: "yoga",
    name: "Triángulo (Trikonasana)",
    position: "De pie",
    modality: ["suave", "dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 3,
    objective: ["cadera", "columna-yoga"],
    description: "Con las piernas separadas y un pie girado hacia afuera, inclinate lateralmente desde la cadera apoyando la mano en la pierna o un bloque, y extendé el otro brazo hacia arriba.",
    howTo: "Pedí que el pecho gire hacia el techo en lugar de caer hacia el piso; luego repitan del otro lado.",
    adaptation: "Apoyar la mano en un bloque o en la espinilla en lugar de buscar el piso.",
    seriesDefault: 1,
  },
  {
    id: "yoga-010",
    discipline: "yoga",
    name: "Postura de la cobra (Bhujangasana)",
    position: "Prono",
    modality: ["dinamico"],
    level: ["inicial", "intermedio"],
    moment: 3,
    objective: ["columna-yoga"],
    avoid: ["Embarazo / posparto"],
    description: "Boca abajo con las manos debajo de los hombros, elevá el pecho del piso usando principalmente los músculos de la espalda, manteniendo los codos apenas flexionados y cerca del cuerpo.",
    howTo: "Pedí que alarguen la nuca en vez de echar la cabeza hacia atrás.",
    adaptation: "Elevar solo unos centímetros el pecho, apoyando los antebrazos en el piso (esfinge).",
    seriesDefault: 2,
  },
  {
    id: "yoga-011",
    discipline: "yoga",
    name: "Media luna (Ardha Chandrasana)",
    position: "De pie",
    modality: ["dinamico"],
    level: ["avanzado"],
    moment: 4,
    objective: ["fuerza-yoga", "enraizamiento"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Desde triángulo, apoyá una mano en el piso o un bloque y elevá la pierna de atrás mientras el torso rota hacia arriba, sosteniendo el equilibrio con la mirada al frente.",
    howTo: "Pedí que empujen el talón de la pierna elevada hacia atrás, como contra una pared.",
    adaptation: "Practicar cerca de una pared para apoyar la pierna elevada o mantener una mano en la cadera.",
    seriesDefault: 1,
  },
  {
    id: "yoga-012",
    discipline: "yoga",
    name: "Media paloma reclinada con soporte",
    position: "Supino",
    modality: ["suave", "restaurativo"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 4,
    objective: ["cadera"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Acostada, cruzá un tobillo sobre la rodilla opuesta formando un cuatro, y sostené la pierna de abajo con las manos, acercando suavemente las piernas hacia el pecho.",
    howTo: "Pedí que la cabeza y los hombros se mantengan apoyados y relajados; luego repitan del otro lado.",
    adaptation: "Mantener el pie apoyado en el piso en lugar de acercar las piernas al pecho.",
    seriesDefault: 1,
  },
  {
    id: "yoga-013",
    discipline: "yoga",
    name: "Águila (Garudasana)",
    position: "De pie",
    modality: ["dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 4,
    objective: ["enraizamiento", "cadera"],
    avoid: ["Problemas de cadera / prótesis", "Post-cirugía de rodilla"],
    description: "De pie en un solo apoyo, cruzá un muslo sobre el otro enganchando el pie si es posible, y envolvé los brazos entre sí, buscando un punto fijo para sostener el equilibrio.",
    howTo: "Pedí que fijen la mirada en un punto quieto antes de cruzar los brazos.",
    adaptation: "Apoyar apenas la punta del pie en el piso en lugar de enganchar la pierna.",
    seriesDefault: 1,
  },
  {
    id: "yoga-014",
    discipline: "yoga",
    name: "Camello con apoyo (Ustrasana modificada)",
    position: "De rodillas",
    modality: ["dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 4,
    objective: ["columna-yoga"],
    avoid: ["Hipermovilidad", "Hernia de disco lumbar"],
    description: "De rodillas con las manos en la zona lumbar, empujá las caderas hacia adelante y abrí el pecho hacia arriba, extendiendo la columna sin dejar caer la cabeza de golpe.",
    howTo: "Pedí que empiecen el movimiento empujando las caderas antes de abrir el pecho.",
    adaptation: "Mantener las manos en la zona lumbar durante toda la postura, sin llevarlas a los talones.",
    seriesDefault: 1,
  },
  {
    id: "yoga-015",
    discipline: "yoga",
    name: "Flujo Guerrero II a triángulo",
    position: "De pie",
    modality: ["dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 5,
    objective: ["fuerza-yoga", "enraizamiento"],
    description: "Desde Guerrero II, extendé la pierna delantera y llevá el torso hacia adelante hasta triángulo, y volvé a flexionar para regresar, uniendo ambas posturas con la respiración.",
    howTo: "Pedí que el movimiento de ida y vuelta siga el ritmo de inhalar y exhalar; alternen el lado en la siguiente ronda.",
    seriesDefault: 2,
  },
  {
    id: "yoga-016",
    discipline: "yoga",
    name: "Secuencia fluida gato-vaca a perro boca abajo",
    position: "Cuadrupedia",
    modality: ["suave", "dinamico"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 5,
    objective: ["columna-yoga"],
    description: "Encadená gato y vaca con la respiración, y en la siguiente exhalación llevá las caderas hacia atrás y arriba hasta perro boca abajo, repitiendo la secuencia varias veces.",
    howTo: "Pedí que cada cambio de postura coincida con una inhalación o una exhalación completa.",
    seriesDefault: 3,
  },
  {
    id: "yoga-017",
    discipline: "yoga",
    name: "Guerrero II a ángulo lateral extendido",
    position: "De pie",
    modality: ["dinamico"],
    level: ["intermedio", "avanzado"],
    moment: 5,
    objective: ["cadera", "enraizamiento"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Desde Guerrero II, apoyá el antebrazo sobre el muslo delantero y extendé el otro brazo por encima de la oreja, formando una línea larga desde el pie de atrás hasta la mano.",
    howTo: "Pedí que la rodilla delantera se mantenga alineada con el segundo dedo del pie; luego repitan del otro lado.",
    adaptation: "Apoyar la mano en un bloque en lugar del antebrazo sobre el muslo.",
    seriesDefault: 1,
  },
  {
    id: "yoga-018",
    discipline: "yoga",
    name: "Zapatero reclinado (Supta Baddha Konasana)",
    position: "Supino",
    modality: ["suave", "restaurativo"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["cadera"],
    avoid: ["Problemas de cadera / prótesis"],
    description: "Acostada con las plantas de los pies unidas y las rodillas apoyadas hacia los costados sobre almohadones, quedate en quietud respirando y soltando el peso de las piernas.",
    howTo: "Pedí que ajusten la altura de los almohadones hasta sentir la cadera completamente sostenida.",
    seriesDefault: 1,
  },
  {
    id: "yoga-019",
    discipline: "yoga",
    name: "Torsión reclinada suave (Supta Matsyendrasana)",
    position: "Supino",
    modality: ["suave", "restaurativo"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["columna-yoga"],
    avoid: ["Hernia de disco lumbar", "Embarazo / posparto"],
    description: "Acostada con las rodillas flexionadas, dejalas caer juntas hacia un costado mientras los brazos se abren en cruz y la mirada busca el lado contrario, respirando con calma.",
    howTo: "Pedí que ambos hombros se mantengan apoyados en el piso; luego repitan hacia el otro costado.",
    adaptation: "Colocar una almohada debajo de las rodillas para reducir el recorrido de la torsión.",
    seriesDefault: 1,
  },
  {
    id: "yoga-020",
    discipline: "yoga",
    name: "Piernas en la pared (Viparita Karani)",
    position: "Supino",
    modality: ["suave", "restaurativo"],
    level: ["inicial", "intermedio", "avanzado"],
    moment: 6,
    objective: ["enraizamiento"],
    avoid: ["Embarazo / posparto"],
    description: "Acostada cerca de una pared, apoyá las piernas extendidas hacia arriba contra ella y dejá los brazos relajados a los costados, permaneciendo en quietud varios minutos con los ojos cerrados.",
    howTo: "Pedí que acerquen o alejen la cadera de la pared hasta sentir las piernas cómodas.",
    adaptation: "Doblar las rodillas o alejar la cadera de la pared si sienten tirantez detrás de las piernas.",
    seriesDefault: 1,
  },
]
